// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetFriendListInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetFriendListInfoScRsp.proto</summary>
public static partial class GetFriendListInfoScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetFriendListInfoScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetFriendListInfoScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxHZXRGcmllbmRMaXN0SW5mb1NjUnNwLnByb3RvIm8KFkdldEZyaWVuZExp",
          "c3RJbmZvU2NSc3ASIQoLZEdERURIQUZLSVAYCyADKAsyDC5LRkZCTEdDR1BJ",
          "SxIhCgtrREdMRkZQT09GSRgHIAMoCzIMLkhOT01KT0ROR0ZBEg8KB21fdmFs",
          "dWUYASABKA0iRAoLS0ZGQkxHQ0dQSUsSEgoKcmVtYXJrTmFtZRgPIAEoCRIh",
          "CgtmS0FCR0FKRUVOTRgIIAEoCzIMLkhOT01KT0ROR0ZBItkBCgtITk9NSk9E",
          "TkdGQRIQCghpc0Jhbm5lZBgBIAEoCBITCgtfSGVhZEljb25JRBgMIAEoDRIp",
          "CgtsQVBOSkpDR0NJQxgNIAEoDjIULkZyaWVuZE9ubGluZVN0YXR1c08SEwoL",
          "b0FPQUtBRU1QRkYYAiABKAMSIQoLakNIQ0pGREJGREYYCyABKAsyDC5GRkFQ",
          "SU9HRUdOQxIQCghuaWNrTmFtZRgDIAEoCRISCgpfU2lnbmF0dXJlGAggASgJ",
          "EgsKA3VJRBgFIAEoDRINCgVsZXZlbBgOIAEoDSIsCgtGRkFQSU9HRUdOQxIN",
          "CgVsZXZlbBgKIAEoDRIOCgZyZWFsSUQYBiABKA0qWAoTRnJpZW5kT25saW5l",
          "U3RhdHVzTxIgChxGUklFTkRfT05MSU5FX1NUQVRVU19PRkZMSU5FEAASHwob",
          "RlJJRU5EX09OTElORV9TVEFUVVNfT05MSU5FEAFiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FriendOnlineStatusO), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetFriendListInfoScRsp), global::GetFriendListInfoScRsp.Parser, new[]{ "DGDEDHAFKIP", "KDGLFFPOOFI", "MValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::KFFBLGCGPIK), global::KFFBLGCGPIK.Parser, new[]{ "RemarkName", "FKABGAJEENM" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::HNOMJODNGFA), global::HNOMJODNGFA.Parser, new[]{ "IsBanned", "HeadIconID", "LAPNJJCGCIC", "OAOAKAEMPFF", "JCHCJFDBFDF", "NickName", "Signature", "UID", "Level" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FFAPIOGEGNC), global::FFAPIOGEGNC.Parser, new[]{ "Level", "RealID" }, null, null, null, null)
        }));
  }
  #endregion

}

#region Messages
public sealed partial class GetFriendListInfoScRsp : pb::IMessage<GetFriendListInfoScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetFriendListInfoScRsp> _parser = new pb::MessageParser<GetFriendListInfoScRsp>(() => new GetFriendListInfoScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetFriendListInfoScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetFriendListInfoScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetFriendListInfoScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetFriendListInfoScRsp(GetFriendListInfoScRsp other) : this() {
    dGDEDHAFKIP_ = other.dGDEDHAFKIP_.Clone();
    kDGLFFPOOFI_ = other.kDGLFFPOOFI_.Clone();
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetFriendListInfoScRsp Clone() {
    return new GetFriendListInfoScRsp(this);
  }

  /// <summary>Field number for the "dGDEDHAFKIP" field.</summary>
  public const int DGDEDHAFKIPFieldNumber = 11;
  private static readonly pb::FieldCodec<global::KFFBLGCGPIK> _repeated_dGDEDHAFKIP_codec
      = pb::FieldCodec.ForMessage(90, global::KFFBLGCGPIK.Parser);
  private readonly pbc::RepeatedField<global::KFFBLGCGPIK> dGDEDHAFKIP_ = new pbc::RepeatedField<global::KFFBLGCGPIK>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::KFFBLGCGPIK> DGDEDHAFKIP {
    get { return dGDEDHAFKIP_; }
  }

  /// <summary>Field number for the "kDGLFFPOOFI" field.</summary>
  public const int KDGLFFPOOFIFieldNumber = 7;
  private static readonly pb::FieldCodec<global::HNOMJODNGFA> _repeated_kDGLFFPOOFI_codec
      = pb::FieldCodec.ForMessage(58, global::HNOMJODNGFA.Parser);
  private readonly pbc::RepeatedField<global::HNOMJODNGFA> kDGLFFPOOFI_ = new pbc::RepeatedField<global::HNOMJODNGFA>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HNOMJODNGFA> KDGLFFPOOFI {
    get { return kDGLFFPOOFI_; }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 1;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetFriendListInfoScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetFriendListInfoScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!dGDEDHAFKIP_.Equals(other.dGDEDHAFKIP_)) return false;
    if(!kDGLFFPOOFI_.Equals(other.kDGLFFPOOFI_)) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= dGDEDHAFKIP_.GetHashCode();
    hash ^= kDGLFFPOOFI_.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MValue != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(MValue);
    }
    kDGLFFPOOFI_.WriteTo(output, _repeated_kDGLFFPOOFI_codec);
    dGDEDHAFKIP_.WriteTo(output, _repeated_dGDEDHAFKIP_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MValue != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(MValue);
    }
    kDGLFFPOOFI_.WriteTo(ref output, _repeated_kDGLFFPOOFI_codec);
    dGDEDHAFKIP_.WriteTo(ref output, _repeated_dGDEDHAFKIP_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += dGDEDHAFKIP_.CalculateSize(_repeated_dGDEDHAFKIP_codec);
    size += kDGLFFPOOFI_.CalculateSize(_repeated_kDGLFFPOOFI_codec);
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetFriendListInfoScRsp other) {
    if (other == null) {
      return;
    }
    dGDEDHAFKIP_.Add(other.dGDEDHAFKIP_);
    kDGLFFPOOFI_.Add(other.kDGLFFPOOFI_);
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          MValue = input.ReadUInt32();
          break;
        }
        case 58: {
          kDGLFFPOOFI_.AddEntriesFrom(input, _repeated_kDGLFFPOOFI_codec);
          break;
        }
        case 90: {
          dGDEDHAFKIP_.AddEntriesFrom(input, _repeated_dGDEDHAFKIP_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          MValue = input.ReadUInt32();
          break;
        }
        case 58: {
          kDGLFFPOOFI_.AddEntriesFrom(ref input, _repeated_kDGLFFPOOFI_codec);
          break;
        }
        case 90: {
          dGDEDHAFKIP_.AddEntriesFrom(ref input, _repeated_dGDEDHAFKIP_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class KFFBLGCGPIK : pb::IMessage<KFFBLGCGPIK>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<KFFBLGCGPIK> _parser = new pb::MessageParser<KFFBLGCGPIK>(() => new KFFBLGCGPIK());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<KFFBLGCGPIK> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetFriendListInfoScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KFFBLGCGPIK() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KFFBLGCGPIK(KFFBLGCGPIK other) : this() {
    remarkName_ = other.remarkName_;
    fKABGAJEENM_ = other.fKABGAJEENM_ != null ? other.fKABGAJEENM_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KFFBLGCGPIK Clone() {
    return new KFFBLGCGPIK(this);
  }

  /// <summary>Field number for the "remarkName" field.</summary>
  public const int RemarkNameFieldNumber = 15;
  private string remarkName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string RemarkName {
    get { return remarkName_; }
    set {
      remarkName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "fKABGAJEENM" field.</summary>
  public const int FKABGAJEENMFieldNumber = 8;
  private global::HNOMJODNGFA fKABGAJEENM_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::HNOMJODNGFA FKABGAJEENM {
    get { return fKABGAJEENM_; }
    set {
      fKABGAJEENM_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as KFFBLGCGPIK);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(KFFBLGCGPIK other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RemarkName != other.RemarkName) return false;
    if (!object.Equals(FKABGAJEENM, other.FKABGAJEENM)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RemarkName.Length != 0) hash ^= RemarkName.GetHashCode();
    if (fKABGAJEENM_ != null) hash ^= FKABGAJEENM.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (fKABGAJEENM_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(FKABGAJEENM);
    }
    if (RemarkName.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(RemarkName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (fKABGAJEENM_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(FKABGAJEENM);
    }
    if (RemarkName.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(RemarkName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RemarkName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RemarkName);
    }
    if (fKABGAJEENM_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FKABGAJEENM);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(KFFBLGCGPIK other) {
    if (other == null) {
      return;
    }
    if (other.RemarkName.Length != 0) {
      RemarkName = other.RemarkName;
    }
    if (other.fKABGAJEENM_ != null) {
      if (fKABGAJEENM_ == null) {
        FKABGAJEENM = new global::HNOMJODNGFA();
      }
      FKABGAJEENM.MergeFrom(other.FKABGAJEENM);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 66: {
          if (fKABGAJEENM_ == null) {
            FKABGAJEENM = new global::HNOMJODNGFA();
          }
          input.ReadMessage(FKABGAJEENM);
          break;
        }
        case 122: {
          RemarkName = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 66: {
          if (fKABGAJEENM_ == null) {
            FKABGAJEENM = new global::HNOMJODNGFA();
          }
          input.ReadMessage(FKABGAJEENM);
          break;
        }
        case 122: {
          RemarkName = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}
#endregion


#endregion Designer generated code
