// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetGachaInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetGachaInfoScRsp.proto</summary>
public static partial class GetGachaInfoScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetGachaInfoScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetGachaInfoScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdHZXRHYWNoYUluZm9TY1JzcC5wcm90byKZAQoRR2V0R2FjaGFJbmZvU2NS",
          "c3ASEwoLY0pHQkJMR0xMSEUYDCABKA0SEwoLZ0xDTk5BSE9EQk8YBiABKA0S",
          "IQoLbUdGUEJCQUtPTUkYByADKAsyDC5HTElCREZDT01KShITCgttSFBPTURI",
          "TkxJRBgOIAEoDRIRCglyYW5kb21OdW0YDyABKA0SDwoHbV92YWx1ZRgIIAEo",
          "DSLvAQoLR0xJQkRGQ09NSkoSEgoKaGlzdG9yeVVSTBgKIAEoCRIPCgdnYWNo",
          "YUlEGAQgASgNEhMKC2VEQkdOUENGSEJCGAkgAygNEhYKDmJlZ2luVGltZVN0",
          "YW1wGA8gASgDEhgKEGN1cnJlbnRHYWNoYVRpbWUYCyABKA0SEwoLaklLT0VJ",
          "TE1BSEsYAyABKA0SIQoLZ0FLTEtIT01HQk4YCCABKAsyDC5MQUtGSkVGSURM",
          "QhIUCgxlbmRUaW1lU3RhbXAYAiABKAMSEQoJZGV0YWlsVVJMGA0gASgJEhMK",
          "C25GR0hNQkNJSkNEGAwgAygNImEKC0xBS0ZKRUZJRExCEigKC25MRERGSkNB",
          "SElBGAEgAygLMhMuR2FjaGFDZWlsaW5nQXZhdGFyEhMKC2tNS0RKREpGSEJK",
          "GAUgASgNEhMKC2tLS09NQkJGQU9QGA8gASgIIjsKEkdhY2hhQ2VpbGluZ0F2",
          "YXRhchITCgtyZXBlYXRlZENudBgHIAEoDRIQCghhdmF0YXJJZBgGIAEoDWIG",
          "cHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGachaInfoScRsp), global::GetGachaInfoScRsp.Parser, new[]{ "CJGBBLGLLHE", "GLCNNAHODBO", "MGFPBBAKOMI", "MHPOMDHNLID", "RandomNum", "MValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GLIBDFCOMJJ), global::GLIBDFCOMJJ.Parser, new[]{ "HistoryURL", "GachaID", "EDBGNPCFHBB", "BeginTimeStamp", "CurrentGachaTime", "JIKOEILMAHK", "GAKLKHOMGBN", "EndTimeStamp", "DetailURL", "NFGHMBCIJCD" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LAKFJEFIDLB), global::LAKFJEFIDLB.Parser, new[]{ "NLDDFJCAHIA", "KMKDJDJFHBJ", "KKKOMBBFAOP" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::GachaCeilingAvatar), global::GachaCeilingAvatar.Parser, new[]{ "RepeatedCnt", "AvatarId" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetGachaInfoScRsp : pb::IMessage<GetGachaInfoScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetGachaInfoScRsp> _parser = new pb::MessageParser<GetGachaInfoScRsp>(() => new GetGachaInfoScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetGachaInfoScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetGachaInfoScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGachaInfoScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGachaInfoScRsp(GetGachaInfoScRsp other) : this() {
    cJGBBLGLLHE_ = other.cJGBBLGLLHE_;
    gLCNNAHODBO_ = other.gLCNNAHODBO_;
    mGFPBBAKOMI_ = other.mGFPBBAKOMI_.Clone();
    mHPOMDHNLID_ = other.mHPOMDHNLID_;
    randomNum_ = other.randomNum_;
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGachaInfoScRsp Clone() {
    return new GetGachaInfoScRsp(this);
  }

  /// <summary>Field number for the "cJGBBLGLLHE" field.</summary>
  public const int CJGBBLGLLHEFieldNumber = 12;
  private uint cJGBBLGLLHE_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CJGBBLGLLHE {
    get { return cJGBBLGLLHE_; }
    set {
      cJGBBLGLLHE_ = value;
    }
  }

  /// <summary>Field number for the "gLCNNAHODBO" field.</summary>
  public const int GLCNNAHODBOFieldNumber = 6;
  private uint gLCNNAHODBO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GLCNNAHODBO {
    get { return gLCNNAHODBO_; }
    set {
      gLCNNAHODBO_ = value;
    }
  }

  /// <summary>Field number for the "mGFPBBAKOMI" field.</summary>
  public const int MGFPBBAKOMIFieldNumber = 7;
  private static readonly pb::FieldCodec<global::GLIBDFCOMJJ> _repeated_mGFPBBAKOMI_codec
      = pb::FieldCodec.ForMessage(58, global::GLIBDFCOMJJ.Parser);
  private readonly pbc::RepeatedField<global::GLIBDFCOMJJ> mGFPBBAKOMI_ = new pbc::RepeatedField<global::GLIBDFCOMJJ>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::GLIBDFCOMJJ> MGFPBBAKOMI {
    get { return mGFPBBAKOMI_; }
  }

  /// <summary>Field number for the "mHPOMDHNLID" field.</summary>
  public const int MHPOMDHNLIDFieldNumber = 14;
  private uint mHPOMDHNLID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MHPOMDHNLID {
    get { return mHPOMDHNLID_; }
    set {
      mHPOMDHNLID_ = value;
    }
  }

  /// <summary>Field number for the "randomNum" field.</summary>
  public const int RandomNumFieldNumber = 15;
  private uint randomNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RandomNum {
    get { return randomNum_; }
    set {
      randomNum_ = value;
    }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 8;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetGachaInfoScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetGachaInfoScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CJGBBLGLLHE != other.CJGBBLGLLHE) return false;
    if (GLCNNAHODBO != other.GLCNNAHODBO) return false;
    if(!mGFPBBAKOMI_.Equals(other.mGFPBBAKOMI_)) return false;
    if (MHPOMDHNLID != other.MHPOMDHNLID) return false;
    if (RandomNum != other.RandomNum) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CJGBBLGLLHE != 0) hash ^= CJGBBLGLLHE.GetHashCode();
    if (GLCNNAHODBO != 0) hash ^= GLCNNAHODBO.GetHashCode();
    hash ^= mGFPBBAKOMI_.GetHashCode();
    if (MHPOMDHNLID != 0) hash ^= MHPOMDHNLID.GetHashCode();
    if (RandomNum != 0) hash ^= RandomNum.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (GLCNNAHODBO != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(GLCNNAHODBO);
    }
    mGFPBBAKOMI_.WriteTo(output, _repeated_mGFPBBAKOMI_codec);
    if (MValue != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(MValue);
    }
    if (CJGBBLGLLHE != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(CJGBBLGLLHE);
    }
    if (MHPOMDHNLID != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(MHPOMDHNLID);
    }
    if (RandomNum != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(RandomNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (GLCNNAHODBO != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(GLCNNAHODBO);
    }
    mGFPBBAKOMI_.WriteTo(ref output, _repeated_mGFPBBAKOMI_codec);
    if (MValue != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(MValue);
    }
    if (CJGBBLGLLHE != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(CJGBBLGLLHE);
    }
    if (MHPOMDHNLID != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(MHPOMDHNLID);
    }
    if (RandomNum != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(RandomNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CJGBBLGLLHE != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CJGBBLGLLHE);
    }
    if (GLCNNAHODBO != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GLCNNAHODBO);
    }
    size += mGFPBBAKOMI_.CalculateSize(_repeated_mGFPBBAKOMI_codec);
    if (MHPOMDHNLID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MHPOMDHNLID);
    }
    if (RandomNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RandomNum);
    }
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetGachaInfoScRsp other) {
    if (other == null) {
      return;
    }
    if (other.CJGBBLGLLHE != 0) {
      CJGBBLGLLHE = other.CJGBBLGLLHE;
    }
    if (other.GLCNNAHODBO != 0) {
      GLCNNAHODBO = other.GLCNNAHODBO;
    }
    mGFPBBAKOMI_.Add(other.mGFPBBAKOMI_);
    if (other.MHPOMDHNLID != 0) {
      MHPOMDHNLID = other.MHPOMDHNLID;
    }
    if (other.RandomNum != 0) {
      RandomNum = other.RandomNum;
    }
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 48: {
          GLCNNAHODBO = input.ReadUInt32();
          break;
        }
        case 58: {
          mGFPBBAKOMI_.AddEntriesFrom(input, _repeated_mGFPBBAKOMI_codec);
          break;
        }
        case 64: {
          MValue = input.ReadUInt32();
          break;
        }
        case 96: {
          CJGBBLGLLHE = input.ReadUInt32();
          break;
        }
        case 112: {
          MHPOMDHNLID = input.ReadUInt32();
          break;
        }
        case 120: {
          RandomNum = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 48: {
          GLCNNAHODBO = input.ReadUInt32();
          break;
        }
        case 58: {
          mGFPBBAKOMI_.AddEntriesFrom(ref input, _repeated_mGFPBBAKOMI_codec);
          break;
        }
        case 64: {
          MValue = input.ReadUInt32();
          break;
        }
        case 96: {
          CJGBBLGLLHE = input.ReadUInt32();
          break;
        }
        case 112: {
          MHPOMDHNLID = input.ReadUInt32();
          break;
        }
        case 120: {
          RandomNum = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class GLIBDFCOMJJ : pb::IMessage<GLIBDFCOMJJ>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GLIBDFCOMJJ> _parser = new pb::MessageParser<GLIBDFCOMJJ>(() => new GLIBDFCOMJJ());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GLIBDFCOMJJ> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetGachaInfoScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GLIBDFCOMJJ() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GLIBDFCOMJJ(GLIBDFCOMJJ other) : this() {
    historyURL_ = other.historyURL_;
    gachaID_ = other.gachaID_;
    eDBGNPCFHBB_ = other.eDBGNPCFHBB_.Clone();
    beginTimeStamp_ = other.beginTimeStamp_;
    currentGachaTime_ = other.currentGachaTime_;
    jIKOEILMAHK_ = other.jIKOEILMAHK_;
    gAKLKHOMGBN_ = other.gAKLKHOMGBN_ != null ? other.gAKLKHOMGBN_.Clone() : null;
    endTimeStamp_ = other.endTimeStamp_;
    detailURL_ = other.detailURL_;
    nFGHMBCIJCD_ = other.nFGHMBCIJCD_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GLIBDFCOMJJ Clone() {
    return new GLIBDFCOMJJ(this);
  }

  /// <summary>Field number for the "historyURL" field.</summary>
  public const int HistoryURLFieldNumber = 10;
  private string historyURL_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HistoryURL {
    get { return historyURL_; }
    set {
      historyURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "gachaID" field.</summary>
  public const int GachaIDFieldNumber = 4;
  private uint gachaID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GachaID {
    get { return gachaID_; }
    set {
      gachaID_ = value;
    }
  }

  /// <summary>Field number for the "eDBGNPCFHBB" field.</summary>
  public const int EDBGNPCFHBBFieldNumber = 9;
  private static readonly pb::FieldCodec<uint> _repeated_eDBGNPCFHBB_codec
      = pb::FieldCodec.ForUInt32(74);
  private readonly pbc::RepeatedField<uint> eDBGNPCFHBB_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> EDBGNPCFHBB {
    get { return eDBGNPCFHBB_; }
  }

  /// <summary>Field number for the "beginTimeStamp" field.</summary>
  public const int BeginTimeStampFieldNumber = 15;
  private long beginTimeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long BeginTimeStamp {
    get { return beginTimeStamp_; }
    set {
      beginTimeStamp_ = value;
    }
  }

  /// <summary>Field number for the "currentGachaTime" field.</summary>
  public const int CurrentGachaTimeFieldNumber = 11;
  private uint currentGachaTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CurrentGachaTime {
    get { return currentGachaTime_; }
    set {
      currentGachaTime_ = value;
    }
  }

  /// <summary>Field number for the "jIKOEILMAHK" field.</summary>
  public const int JIKOEILMAHKFieldNumber = 3;
  private uint jIKOEILMAHK_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint JIKOEILMAHK {
    get { return jIKOEILMAHK_; }
    set {
      jIKOEILMAHK_ = value;
    }
  }

  /// <summary>Field number for the "gAKLKHOMGBN" field.</summary>
  public const int GAKLKHOMGBNFieldNumber = 8;
  private global::LAKFJEFIDLB gAKLKHOMGBN_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LAKFJEFIDLB GAKLKHOMGBN {
    get { return gAKLKHOMGBN_; }
    set {
      gAKLKHOMGBN_ = value;
    }
  }

  /// <summary>Field number for the "endTimeStamp" field.</summary>
  public const int EndTimeStampFieldNumber = 2;
  private long endTimeStamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long EndTimeStamp {
    get { return endTimeStamp_; }
    set {
      endTimeStamp_ = value;
    }
  }

  /// <summary>Field number for the "detailURL" field.</summary>
  public const int DetailURLFieldNumber = 13;
  private string detailURL_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DetailURL {
    get { return detailURL_; }
    set {
      detailURL_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "nFGHMBCIJCD" field.</summary>
  public const int NFGHMBCIJCDFieldNumber = 12;
  private static readonly pb::FieldCodec<uint> _repeated_nFGHMBCIJCD_codec
      = pb::FieldCodec.ForUInt32(98);
  private readonly pbc::RepeatedField<uint> nFGHMBCIJCD_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> NFGHMBCIJCD {
    get { return nFGHMBCIJCD_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GLIBDFCOMJJ);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GLIBDFCOMJJ other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HistoryURL != other.HistoryURL) return false;
    if (GachaID != other.GachaID) return false;
    if(!eDBGNPCFHBB_.Equals(other.eDBGNPCFHBB_)) return false;
    if (BeginTimeStamp != other.BeginTimeStamp) return false;
    if (CurrentGachaTime != other.CurrentGachaTime) return false;
    if (JIKOEILMAHK != other.JIKOEILMAHK) return false;
    if (!object.Equals(GAKLKHOMGBN, other.GAKLKHOMGBN)) return false;
    if (EndTimeStamp != other.EndTimeStamp) return false;
    if (DetailURL != other.DetailURL) return false;
    if(!nFGHMBCIJCD_.Equals(other.nFGHMBCIJCD_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HistoryURL.Length != 0) hash ^= HistoryURL.GetHashCode();
    if (GachaID != 0) hash ^= GachaID.GetHashCode();
    hash ^= eDBGNPCFHBB_.GetHashCode();
    if (BeginTimeStamp != 0L) hash ^= BeginTimeStamp.GetHashCode();
    if (CurrentGachaTime != 0) hash ^= CurrentGachaTime.GetHashCode();
    if (JIKOEILMAHK != 0) hash ^= JIKOEILMAHK.GetHashCode();
    if (gAKLKHOMGBN_ != null) hash ^= GAKLKHOMGBN.GetHashCode();
    if (EndTimeStamp != 0L) hash ^= EndTimeStamp.GetHashCode();
    if (DetailURL.Length != 0) hash ^= DetailURL.GetHashCode();
    hash ^= nFGHMBCIJCD_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (EndTimeStamp != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(EndTimeStamp);
    }
    if (JIKOEILMAHK != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(JIKOEILMAHK);
    }
    if (GachaID != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(GachaID);
    }
    if (gAKLKHOMGBN_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(GAKLKHOMGBN);
    }
    eDBGNPCFHBB_.WriteTo(output, _repeated_eDBGNPCFHBB_codec);
    if (HistoryURL.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(HistoryURL);
    }
    if (CurrentGachaTime != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(CurrentGachaTime);
    }
    nFGHMBCIJCD_.WriteTo(output, _repeated_nFGHMBCIJCD_codec);
    if (DetailURL.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(DetailURL);
    }
    if (BeginTimeStamp != 0L) {
      output.WriteRawTag(120);
      output.WriteInt64(BeginTimeStamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (EndTimeStamp != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(EndTimeStamp);
    }
    if (JIKOEILMAHK != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(JIKOEILMAHK);
    }
    if (GachaID != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(GachaID);
    }
    if (gAKLKHOMGBN_ != null) {
      output.WriteRawTag(66);
      output.WriteMessage(GAKLKHOMGBN);
    }
    eDBGNPCFHBB_.WriteTo(ref output, _repeated_eDBGNPCFHBB_codec);
    if (HistoryURL.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(HistoryURL);
    }
    if (CurrentGachaTime != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(CurrentGachaTime);
    }
    nFGHMBCIJCD_.WriteTo(ref output, _repeated_nFGHMBCIJCD_codec);
    if (DetailURL.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(DetailURL);
    }
    if (BeginTimeStamp != 0L) {
      output.WriteRawTag(120);
      output.WriteInt64(BeginTimeStamp);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HistoryURL.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HistoryURL);
    }
    if (GachaID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaID);
    }
    size += eDBGNPCFHBB_.CalculateSize(_repeated_eDBGNPCFHBB_codec);
    if (BeginTimeStamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(BeginTimeStamp);
    }
    if (CurrentGachaTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentGachaTime);
    }
    if (JIKOEILMAHK != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JIKOEILMAHK);
    }
    if (gAKLKHOMGBN_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GAKLKHOMGBN);
    }
    if (EndTimeStamp != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(EndTimeStamp);
    }
    if (DetailURL.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DetailURL);
    }
    size += nFGHMBCIJCD_.CalculateSize(_repeated_nFGHMBCIJCD_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GLIBDFCOMJJ other) {
    if (other == null) {
      return;
    }
    if (other.HistoryURL.Length != 0) {
      HistoryURL = other.HistoryURL;
    }
    if (other.GachaID != 0) {
      GachaID = other.GachaID;
    }
    eDBGNPCFHBB_.Add(other.eDBGNPCFHBB_);
    if (other.BeginTimeStamp != 0L) {
      BeginTimeStamp = other.BeginTimeStamp;
    }
    if (other.CurrentGachaTime != 0) {
      CurrentGachaTime = other.CurrentGachaTime;
    }
    if (other.JIKOEILMAHK != 0) {
      JIKOEILMAHK = other.JIKOEILMAHK;
    }
    if (other.gAKLKHOMGBN_ != null) {
      if (gAKLKHOMGBN_ == null) {
        GAKLKHOMGBN = new global::LAKFJEFIDLB();
      }
      GAKLKHOMGBN.MergeFrom(other.GAKLKHOMGBN);
    }
    if (other.EndTimeStamp != 0L) {
      EndTimeStamp = other.EndTimeStamp;
    }
    if (other.DetailURL.Length != 0) {
      DetailURL = other.DetailURL;
    }
    nFGHMBCIJCD_.Add(other.nFGHMBCIJCD_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          EndTimeStamp = input.ReadInt64();
          break;
        }
        case 24: {
          JIKOEILMAHK = input.ReadUInt32();
          break;
        }
        case 32: {
          GachaID = input.ReadUInt32();
          break;
        }
        case 66: {
          if (gAKLKHOMGBN_ == null) {
            GAKLKHOMGBN = new global::LAKFJEFIDLB();
          }
          input.ReadMessage(GAKLKHOMGBN);
          break;
        }
        case 74:
        case 72: {
          eDBGNPCFHBB_.AddEntriesFrom(input, _repeated_eDBGNPCFHBB_codec);
          break;
        }
        case 82: {
          HistoryURL = input.ReadString();
          break;
        }
        case 88: {
          CurrentGachaTime = input.ReadUInt32();
          break;
        }
        case 98:
        case 96: {
          nFGHMBCIJCD_.AddEntriesFrom(input, _repeated_nFGHMBCIJCD_codec);
          break;
        }
        case 106: {
          DetailURL = input.ReadString();
          break;
        }
        case 120: {
          BeginTimeStamp = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          EndTimeStamp = input.ReadInt64();
          break;
        }
        case 24: {
          JIKOEILMAHK = input.ReadUInt32();
          break;
        }
        case 32: {
          GachaID = input.ReadUInt32();
          break;
        }
        case 66: {
          if (gAKLKHOMGBN_ == null) {
            GAKLKHOMGBN = new global::LAKFJEFIDLB();
          }
          input.ReadMessage(GAKLKHOMGBN);
          break;
        }
        case 74:
        case 72: {
          eDBGNPCFHBB_.AddEntriesFrom(ref input, _repeated_eDBGNPCFHBB_codec);
          break;
        }
        case 82: {
          HistoryURL = input.ReadString();
          break;
        }
        case 88: {
          CurrentGachaTime = input.ReadUInt32();
          break;
        }
        case 98:
        case 96: {
          nFGHMBCIJCD_.AddEntriesFrom(ref input, _repeated_nFGHMBCIJCD_codec);
          break;
        }
        case 106: {
          DetailURL = input.ReadString();
          break;
        }
        case 120: {
          BeginTimeStamp = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LAKFJEFIDLB : pb::IMessage<LAKFJEFIDLB>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LAKFJEFIDLB> _parser = new pb::MessageParser<LAKFJEFIDLB>(() => new LAKFJEFIDLB());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LAKFJEFIDLB> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetGachaInfoScRspReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LAKFJEFIDLB() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LAKFJEFIDLB(LAKFJEFIDLB other) : this() {
    nLDDFJCAHIA_ = other.nLDDFJCAHIA_.Clone();
    kMKDJDJFHBJ_ = other.kMKDJDJFHBJ_;
    kKKOMBBFAOP_ = other.kKKOMBBFAOP_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LAKFJEFIDLB Clone() {
    return new LAKFJEFIDLB(this);
  }

  /// <summary>Field number for the "nLDDFJCAHIA" field.</summary>
  public const int NLDDFJCAHIAFieldNumber = 1;
  private static readonly pb::FieldCodec<global::GachaCeilingAvatar> _repeated_nLDDFJCAHIA_codec
      = pb::FieldCodec.ForMessage(10, global::GachaCeilingAvatar.Parser);
  private readonly pbc::RepeatedField<global::GachaCeilingAvatar> nLDDFJCAHIA_ = new pbc::RepeatedField<global::GachaCeilingAvatar>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::GachaCeilingAvatar> NLDDFJCAHIA {
    get { return nLDDFJCAHIA_; }
  }

  /// <summary>Field number for the "kMKDJDJFHBJ" field.</summary>
  public const int KMKDJDJFHBJFieldNumber = 5;
  private uint kMKDJDJFHBJ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint KMKDJDJFHBJ {
    get { return kMKDJDJFHBJ_; }
    set {
      kMKDJDJFHBJ_ = value;
    }
  }

  /// <summary>Field number for the "kKKOMBBFAOP" field.</summary>
  public const int KKKOMBBFAOPFieldNumber = 15;
  private bool kKKOMBBFAOP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool KKKOMBBFAOP {
    get { return kKKOMBBFAOP_; }
    set {
      kKKOMBBFAOP_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LAKFJEFIDLB);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LAKFJEFIDLB other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!nLDDFJCAHIA_.Equals(other.nLDDFJCAHIA_)) return false;
    if (KMKDJDJFHBJ != other.KMKDJDJFHBJ) return false;
    if (KKKOMBBFAOP != other.KKKOMBBFAOP) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= nLDDFJCAHIA_.GetHashCode();
    if (KMKDJDJFHBJ != 0) hash ^= KMKDJDJFHBJ.GetHashCode();
    if (KKKOMBBFAOP != false) hash ^= KKKOMBBFAOP.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    nLDDFJCAHIA_.WriteTo(output, _repeated_nLDDFJCAHIA_codec);
    if (KMKDJDJFHBJ != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(KMKDJDJFHBJ);
    }
    if (KKKOMBBFAOP != false) {
      output.WriteRawTag(120);
      output.WriteBool(KKKOMBBFAOP);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    nLDDFJCAHIA_.WriteTo(ref output, _repeated_nLDDFJCAHIA_codec);
    if (KMKDJDJFHBJ != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(KMKDJDJFHBJ);
    }
    if (KKKOMBBFAOP != false) {
      output.WriteRawTag(120);
      output.WriteBool(KKKOMBBFAOP);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += nLDDFJCAHIA_.CalculateSize(_repeated_nLDDFJCAHIA_codec);
    if (KMKDJDJFHBJ != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KMKDJDJFHBJ);
    }
    if (KKKOMBBFAOP != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LAKFJEFIDLB other) {
    if (other == null) {
      return;
    }
    nLDDFJCAHIA_.Add(other.nLDDFJCAHIA_);
    if (other.KMKDJDJFHBJ != 0) {
      KMKDJDJFHBJ = other.KMKDJDJFHBJ;
    }
    if (other.KKKOMBBFAOP != false) {
      KKKOMBBFAOP = other.KKKOMBBFAOP;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          nLDDFJCAHIA_.AddEntriesFrom(input, _repeated_nLDDFJCAHIA_codec);
          break;
        }
        case 40: {
          KMKDJDJFHBJ = input.ReadUInt32();
          break;
        }
        case 120: {
          KKKOMBBFAOP = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          nLDDFJCAHIA_.AddEntriesFrom(ref input, _repeated_nLDDFJCAHIA_codec);
          break;
        }
        case 40: {
          KMKDJDJFHBJ = input.ReadUInt32();
          break;
        }
        case 120: {
          KKKOMBBFAOP = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class GachaCeilingAvatar : pb::IMessage<GachaCeilingAvatar>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GachaCeilingAvatar> _parser = new pb::MessageParser<GachaCeilingAvatar>(() => new GachaCeilingAvatar());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GachaCeilingAvatar> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetGachaInfoScRspReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GachaCeilingAvatar() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GachaCeilingAvatar(GachaCeilingAvatar other) : this() {
    repeatedCnt_ = other.repeatedCnt_;
    avatarId_ = other.avatarId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GachaCeilingAvatar Clone() {
    return new GachaCeilingAvatar(this);
  }

  /// <summary>Field number for the "repeatedCnt" field.</summary>
  public const int RepeatedCntFieldNumber = 7;
  private uint repeatedCnt_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RepeatedCnt {
    get { return repeatedCnt_; }
    set {
      repeatedCnt_ = value;
    }
  }

  /// <summary>Field number for the "avatarId" field.</summary>
  public const int AvatarIdFieldNumber = 6;
  private uint avatarId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AvatarId {
    get { return avatarId_; }
    set {
      avatarId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GachaCeilingAvatar);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GachaCeilingAvatar other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RepeatedCnt != other.RepeatedCnt) return false;
    if (AvatarId != other.AvatarId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RepeatedCnt != 0) hash ^= RepeatedCnt.GetHashCode();
    if (AvatarId != 0) hash ^= AvatarId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AvatarId != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(AvatarId);
    }
    if (RepeatedCnt != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(RepeatedCnt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AvatarId != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(AvatarId);
    }
    if (RepeatedCnt != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(RepeatedCnt);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RepeatedCnt != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RepeatedCnt);
    }
    if (AvatarId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AvatarId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GachaCeilingAvatar other) {
    if (other == null) {
      return;
    }
    if (other.RepeatedCnt != 0) {
      RepeatedCnt = other.RepeatedCnt;
    }
    if (other.AvatarId != 0) {
      AvatarId = other.AvatarId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 48: {
          AvatarId = input.ReadUInt32();
          break;
        }
        case 56: {
          RepeatedCnt = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 48: {
          AvatarId = input.ReadUInt32();
          break;
        }
        case 56: {
          RepeatedCnt = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
