// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetLevelRewardTakenListScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetLevelRewardTakenListScRsp.proto</summary>
public static partial class GetLevelRewardTakenListScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetLevelRewardTakenListScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetLevelRewardTakenListScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiJHZXRMZXZlbFJld2FyZFRha2VuTGlzdFNjUnNwLnByb3RvIkQKHEdldExl",
          "dmVsUmV3YXJkVGFrZW5MaXN0U2NSc3ASEwoLYkVEQ0dCSk9HR0MYDiADKA0S",
          "DwoHbV92YWx1ZRgGIAEoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetLevelRewardTakenListScRsp), global::GetLevelRewardTakenListScRsp.Parser, new[]{ "BEDCGBJOGGC", "MValue" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetLevelRewardTakenListScRsp : pb::IMessage<GetLevelRewardTakenListScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetLevelRewardTakenListScRsp> _parser = new pb::MessageParser<GetLevelRewardTakenListScRsp>(() => new GetLevelRewardTakenListScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetLevelRewardTakenListScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetLevelRewardTakenListScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetLevelRewardTakenListScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetLevelRewardTakenListScRsp(GetLevelRewardTakenListScRsp other) : this() {
    bEDCGBJOGGC_ = other.bEDCGBJOGGC_.Clone();
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetLevelRewardTakenListScRsp Clone() {
    return new GetLevelRewardTakenListScRsp(this);
  }

  /// <summary>Field number for the "bEDCGBJOGGC" field.</summary>
  public const int BEDCGBJOGGCFieldNumber = 14;
  private static readonly pb::FieldCodec<uint> _repeated_bEDCGBJOGGC_codec
      = pb::FieldCodec.ForUInt32(114);
  private readonly pbc::RepeatedField<uint> bEDCGBJOGGC_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> BEDCGBJOGGC {
    get { return bEDCGBJOGGC_; }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 6;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetLevelRewardTakenListScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetLevelRewardTakenListScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!bEDCGBJOGGC_.Equals(other.bEDCGBJOGGC_)) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= bEDCGBJOGGC_.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MValue != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(MValue);
    }
    bEDCGBJOGGC_.WriteTo(output, _repeated_bEDCGBJOGGC_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MValue != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(MValue);
    }
    bEDCGBJOGGC_.WriteTo(ref output, _repeated_bEDCGBJOGGC_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += bEDCGBJOGGC_.CalculateSize(_repeated_bEDCGBJOGGC_codec);
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetLevelRewardTakenListScRsp other) {
    if (other == null) {
      return;
    }
    bEDCGBJOGGC_.Add(other.bEDCGBJOGGC_);
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 48: {
          MValue = input.ReadUInt32();
          break;
        }
        case 114:
        case 112: {
          bEDCGBJOGGC_.AddEntriesFrom(input, _repeated_bEDCGBJOGGC_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 48: {
          MValue = input.ReadUInt32();
          break;
        }
        case 114:
        case 112: {
          bEDCGBJOGGC_.AddEntriesFrom(ref input, _repeated_bEDCGBJOGGC_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code