// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetMissionEventDataScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetMissionEventDataScRsp.proto</summary>
public static partial class GetMissionEventDataScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetMissionEventDataScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetMissionEventDataScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch5HZXRNaXNzaW9uRXZlbnREYXRhU2NSc3AucHJvdG8iYwoYR2V0TWlzc2lv",
          "bkV2ZW50RGF0YVNjUnNwEg8KB21fdmFsdWUYAyABKA0SIQoLakdNQ1BQTUtP",
          "Q04YASADKAsyDC5NaXNzaW9uRGF0YRITCgtlS0JCQUNEQUVGTBgKIAEoDSJU",
          "CgtNaXNzaW9uRGF0YRIYChBfQ3VycmVudFByb2dyZXNzGAggASgNEgoKAmlk",
          "GAEgASgNEh8KB19TdGF0dXMYByABKA4yDi5NaXNzaW9uU3RhdHVzKl4KDU1p",
          "c3Npb25TdGF0dXMSEAoMTUlTU0lPTl9OT05FEAASEQoNTUlTU0lPTl9ET0lO",
          "RxABEhIKDk1JU1NJT05fRklOSVNIEAISFAoQTUlTU0lPTl9QUkVQQVJFRBAD",
          "YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MissionStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetMissionEventDataScRsp), global::GetMissionEventDataScRsp.Parser, new[]{ "MValue", "JGMCPPMKOCN", "EKBBACDAEFL" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MissionData), global::MissionData.Parser, new[]{ "CurrentProgress", "Id", "Status" }, null, null, null, null)
        }));
  }
  #endregion

}

#region Messages
public sealed partial class GetMissionEventDataScRsp : pb::IMessage<GetMissionEventDataScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetMissionEventDataScRsp> _parser = new pb::MessageParser<GetMissionEventDataScRsp>(() => new GetMissionEventDataScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetMissionEventDataScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetMissionEventDataScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionEventDataScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionEventDataScRsp(GetMissionEventDataScRsp other) : this() {
    mValue_ = other.mValue_;
    jGMCPPMKOCN_ = other.jGMCPPMKOCN_.Clone();
    eKBBACDAEFL_ = other.eKBBACDAEFL_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionEventDataScRsp Clone() {
    return new GetMissionEventDataScRsp(this);
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 3;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  /// <summary>Field number for the "jGMCPPMKOCN" field.</summary>
  public const int JGMCPPMKOCNFieldNumber = 1;
  private static readonly pb::FieldCodec<global::MissionData> _repeated_jGMCPPMKOCN_codec
      = pb::FieldCodec.ForMessage(10, global::MissionData.Parser);
  private readonly pbc::RepeatedField<global::MissionData> jGMCPPMKOCN_ = new pbc::RepeatedField<global::MissionData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::MissionData> JGMCPPMKOCN {
    get { return jGMCPPMKOCN_; }
  }

  /// <summary>Field number for the "eKBBACDAEFL" field.</summary>
  public const int EKBBACDAEFLFieldNumber = 10;
  private uint eKBBACDAEFL_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EKBBACDAEFL {
    get { return eKBBACDAEFL_; }
    set {
      eKBBACDAEFL_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetMissionEventDataScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetMissionEventDataScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MValue != other.MValue) return false;
    if(!jGMCPPMKOCN_.Equals(other.jGMCPPMKOCN_)) return false;
    if (EKBBACDAEFL != other.EKBBACDAEFL) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MValue != 0) hash ^= MValue.GetHashCode();
    hash ^= jGMCPPMKOCN_.GetHashCode();
    if (EKBBACDAEFL != 0) hash ^= EKBBACDAEFL.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    jGMCPPMKOCN_.WriteTo(output, _repeated_jGMCPPMKOCN_codec);
    if (MValue != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(MValue);
    }
    if (EKBBACDAEFL != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(EKBBACDAEFL);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    jGMCPPMKOCN_.WriteTo(ref output, _repeated_jGMCPPMKOCN_codec);
    if (MValue != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(MValue);
    }
    if (EKBBACDAEFL != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(EKBBACDAEFL);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    size += jGMCPPMKOCN_.CalculateSize(_repeated_jGMCPPMKOCN_codec);
    if (EKBBACDAEFL != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EKBBACDAEFL);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetMissionEventDataScRsp other) {
    if (other == null) {
      return;
    }
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    jGMCPPMKOCN_.Add(other.jGMCPPMKOCN_);
    if (other.EKBBACDAEFL != 0) {
      EKBBACDAEFL = other.EKBBACDAEFL;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          jGMCPPMKOCN_.AddEntriesFrom(input, _repeated_jGMCPPMKOCN_codec);
          break;
        }
        case 24: {
          MValue = input.ReadUInt32();
          break;
        }
        case 80: {
          EKBBACDAEFL = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          jGMCPPMKOCN_.AddEntriesFrom(ref input, _repeated_jGMCPPMKOCN_codec);
          break;
        }
        case 24: {
          MValue = input.ReadUInt32();
          break;
        }
        case 80: {
          EKBBACDAEFL = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}
#endregion


#endregion Designer generated code
