// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetQuestRecordScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetQuestRecordScRsp.proto</summary>
public static partial class GetQuestRecordScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetQuestRecordScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetQuestRecordScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlHZXRRdWVzdFJlY29yZFNjUnNwLnByb3RvIkkKE0dldFF1ZXN0UmVjb3Jk",
          "U2NSc3ASDwoHbV92YWx1ZRgCIAEoDRIhCgtlRVBPQkNKSUVLSRgGIAMoCzIM",
          "LkRHQ0VBQklCSU1NIjwKC0RHQ0VBQklCSU1NEhMKC2VLSUlKQ01MTE5LGA4g",
          "ASgNEhgKEF9DdXJyZW50UHJvZ3Jlc3MYCSABKA1iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetQuestRecordScRsp), global::GetQuestRecordScRsp.Parser, new[]{ "MValue", "EEPOBCJIEKI" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DGCEABIBIMM), global::DGCEABIBIMM.Parser, new[]{ "EKIIJCMLLNK", "CurrentProgress" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetQuestRecordScRsp : pb::IMessage<GetQuestRecordScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetQuestRecordScRsp> _parser = new pb::MessageParser<GetQuestRecordScRsp>(() => new GetQuestRecordScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetQuestRecordScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetQuestRecordScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetQuestRecordScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetQuestRecordScRsp(GetQuestRecordScRsp other) : this() {
    mValue_ = other.mValue_;
    eEPOBCJIEKI_ = other.eEPOBCJIEKI_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetQuestRecordScRsp Clone() {
    return new GetQuestRecordScRsp(this);
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 2;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  /// <summary>Field number for the "eEPOBCJIEKI" field.</summary>
  public const int EEPOBCJIEKIFieldNumber = 6;
  private static readonly pb::FieldCodec<global::DGCEABIBIMM> _repeated_eEPOBCJIEKI_codec
      = pb::FieldCodec.ForMessage(50, global::DGCEABIBIMM.Parser);
  private readonly pbc::RepeatedField<global::DGCEABIBIMM> eEPOBCJIEKI_ = new pbc::RepeatedField<global::DGCEABIBIMM>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::DGCEABIBIMM> EEPOBCJIEKI {
    get { return eEPOBCJIEKI_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetQuestRecordScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetQuestRecordScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MValue != other.MValue) return false;
    if(!eEPOBCJIEKI_.Equals(other.eEPOBCJIEKI_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MValue != 0) hash ^= MValue.GetHashCode();
    hash ^= eEPOBCJIEKI_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MValue != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(MValue);
    }
    eEPOBCJIEKI_.WriteTo(output, _repeated_eEPOBCJIEKI_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MValue != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(MValue);
    }
    eEPOBCJIEKI_.WriteTo(ref output, _repeated_eEPOBCJIEKI_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    size += eEPOBCJIEKI_.CalculateSize(_repeated_eEPOBCJIEKI_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetQuestRecordScRsp other) {
    if (other == null) {
      return;
    }
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    eEPOBCJIEKI_.Add(other.eEPOBCJIEKI_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          MValue = input.ReadUInt32();
          break;
        }
        case 50: {
          eEPOBCJIEKI_.AddEntriesFrom(input, _repeated_eEPOBCJIEKI_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          MValue = input.ReadUInt32();
          break;
        }
        case 50: {
          eEPOBCJIEKI_.AddEntriesFrom(ref input, _repeated_eEPOBCJIEKI_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DGCEABIBIMM : pb::IMessage<DGCEABIBIMM>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DGCEABIBIMM> _parser = new pb::MessageParser<DGCEABIBIMM>(() => new DGCEABIBIMM());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DGCEABIBIMM> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetQuestRecordScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DGCEABIBIMM() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DGCEABIBIMM(DGCEABIBIMM other) : this() {
    eKIIJCMLLNK_ = other.eKIIJCMLLNK_;
    CurrentProgress_ = other.CurrentProgress_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DGCEABIBIMM Clone() {
    return new DGCEABIBIMM(this);
  }

  /// <summary>Field number for the "eKIIJCMLLNK" field.</summary>
  public const int EKIIJCMLLNKFieldNumber = 14;
  private uint eKIIJCMLLNK_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EKIIJCMLLNK {
    get { return eKIIJCMLLNK_; }
    set {
      eKIIJCMLLNK_ = value;
    }
  }

  /// <summary>Field number for the "_CurrentProgress" field.</summary>
  public const int CurrentProgressFieldNumber = 9;
  private uint CurrentProgress_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CurrentProgress {
    get { return CurrentProgress_; }
    set {
      CurrentProgress_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DGCEABIBIMM);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DGCEABIBIMM other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (EKIIJCMLLNK != other.EKIIJCMLLNK) return false;
    if (CurrentProgress != other.CurrentProgress) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (EKIIJCMLLNK != 0) hash ^= EKIIJCMLLNK.GetHashCode();
    if (CurrentProgress != 0) hash ^= CurrentProgress.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (CurrentProgress != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(CurrentProgress);
    }
    if (EKIIJCMLLNK != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(EKIIJCMLLNK);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (CurrentProgress != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(CurrentProgress);
    }
    if (EKIIJCMLLNK != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(EKIIJCMLLNK);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (EKIIJCMLLNK != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EKIIJCMLLNK);
    }
    if (CurrentProgress != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentProgress);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DGCEABIBIMM other) {
    if (other == null) {
      return;
    }
    if (other.EKIIJCMLLNK != 0) {
      EKIIJCMLLNK = other.EKIIJCMLLNK;
    }
    if (other.CurrentProgress != 0) {
      CurrentProgress = other.CurrentProgress;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 72: {
          CurrentProgress = input.ReadUInt32();
          break;
        }
        case 112: {
          EKIIJCMLLNK = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 72: {
          CurrentProgress = input.ReadUInt32();
          break;
        }
        case 112: {
          EKIIJCMLLNK = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
