// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetRaidInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetRaidInfoScRsp.proto</summary>
public static partial class GetRaidInfoScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetRaidInfoScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetRaidInfoScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZHZXRSYWlkSW5mb1NjUnNwLnByb3RvIpwBChBHZXRSYWlkSW5mb1NjUnNw",
          "EiIKGmNoYWxsZW5nZVRha2VuUmV3YXJkSWRMaXN0GAsgAygNEicKEWNoYWxs",
          "ZW5nZVJhaWRMaXN0GAYgAygLMgwuRkxNS0VCSUlHSk8SDwoHcmV0Y29kZRgP",
          "IAEoDRIqChRmaW5pc2hlZFJhaWRJbmZvTGlzdBgDIAMoCzIMLk9FSUZNQUxF",
          "Q0pEIjkKC0ZMTUtFQklJR0pPEhUKDWN1cnJlbnRSYWlkSUQYCSABKA0SEwoL",
          "bU5LQkpES01ORkkYBCABKA0iTQoLT0VJRk1BTEVDSkQSEwoLZE1MTEdOUE1G",
          "UEUYBCADKA0SEgoKd29ybGRMZXZlbBgOIAEoDRIVCg1jdXJyZW50UmFpZElE",
          "GAggASgNYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetRaidInfoScRsp), global::GetRaidInfoScRsp.Parser, new[]{ "ChallengeTakenRewardIdList", "ChallengeRaidList", "Retcode", "FinishedRaidInfoList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FLMKEBIIGJO), global::FLMKEBIIGJO.Parser, new[]{ "CurrentRaidID", "MNKBJDKMNFI" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::OEIFMALECJD), global::OEIFMALECJD.Parser, new[]{ "DMLLGNPMFPE", "WorldLevel", "CurrentRaidID" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetRaidInfoScRsp : pb::IMessage<GetRaidInfoScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetRaidInfoScRsp> _parser = new pb::MessageParser<GetRaidInfoScRsp>(() => new GetRaidInfoScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetRaidInfoScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetRaidInfoScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetRaidInfoScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetRaidInfoScRsp(GetRaidInfoScRsp other) : this() {
    challengeTakenRewardIdList_ = other.challengeTakenRewardIdList_.Clone();
    challengeRaidList_ = other.challengeRaidList_.Clone();
    retcode_ = other.retcode_;
    finishedRaidInfoList_ = other.finishedRaidInfoList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetRaidInfoScRsp Clone() {
    return new GetRaidInfoScRsp(this);
  }

  /// <summary>Field number for the "challengeTakenRewardIdList" field.</summary>
  public const int ChallengeTakenRewardIdListFieldNumber = 11;
  private static readonly pb::FieldCodec<uint> _repeated_challengeTakenRewardIdList_codec
      = pb::FieldCodec.ForUInt32(90);
  private readonly pbc::RepeatedField<uint> challengeTakenRewardIdList_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> ChallengeTakenRewardIdList {
    get { return challengeTakenRewardIdList_; }
  }

  /// <summary>Field number for the "challengeRaidList" field.</summary>
  public const int ChallengeRaidListFieldNumber = 6;
  private static readonly pb::FieldCodec<global::FLMKEBIIGJO> _repeated_challengeRaidList_codec
      = pb::FieldCodec.ForMessage(50, global::FLMKEBIIGJO.Parser);
  private readonly pbc::RepeatedField<global::FLMKEBIIGJO> challengeRaidList_ = new pbc::RepeatedField<global::FLMKEBIIGJO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::FLMKEBIIGJO> ChallengeRaidList {
    get { return challengeRaidList_; }
  }

  /// <summary>Field number for the "retcode" field.</summary>
  public const int RetcodeFieldNumber = 15;
  private uint retcode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Retcode {
    get { return retcode_; }
    set {
      retcode_ = value;
    }
  }

  /// <summary>Field number for the "finishedRaidInfoList" field.</summary>
  public const int FinishedRaidInfoListFieldNumber = 3;
  private static readonly pb::FieldCodec<global::OEIFMALECJD> _repeated_finishedRaidInfoList_codec
      = pb::FieldCodec.ForMessage(26, global::OEIFMALECJD.Parser);
  private readonly pbc::RepeatedField<global::OEIFMALECJD> finishedRaidInfoList_ = new pbc::RepeatedField<global::OEIFMALECJD>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::OEIFMALECJD> FinishedRaidInfoList {
    get { return finishedRaidInfoList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetRaidInfoScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetRaidInfoScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!challengeTakenRewardIdList_.Equals(other.challengeTakenRewardIdList_)) return false;
    if(!challengeRaidList_.Equals(other.challengeRaidList_)) return false;
    if (Retcode != other.Retcode) return false;
    if(!finishedRaidInfoList_.Equals(other.finishedRaidInfoList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= challengeTakenRewardIdList_.GetHashCode();
    hash ^= challengeRaidList_.GetHashCode();
    if (Retcode != 0) hash ^= Retcode.GetHashCode();
    hash ^= finishedRaidInfoList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    finishedRaidInfoList_.WriteTo(output, _repeated_finishedRaidInfoList_codec);
    challengeRaidList_.WriteTo(output, _repeated_challengeRaidList_codec);
    challengeTakenRewardIdList_.WriteTo(output, _repeated_challengeTakenRewardIdList_codec);
    if (Retcode != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(Retcode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    finishedRaidInfoList_.WriteTo(ref output, _repeated_finishedRaidInfoList_codec);
    challengeRaidList_.WriteTo(ref output, _repeated_challengeRaidList_codec);
    challengeTakenRewardIdList_.WriteTo(ref output, _repeated_challengeTakenRewardIdList_codec);
    if (Retcode != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(Retcode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += challengeTakenRewardIdList_.CalculateSize(_repeated_challengeTakenRewardIdList_codec);
    size += challengeRaidList_.CalculateSize(_repeated_challengeRaidList_codec);
    if (Retcode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
    }
    size += finishedRaidInfoList_.CalculateSize(_repeated_finishedRaidInfoList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetRaidInfoScRsp other) {
    if (other == null) {
      return;
    }
    challengeTakenRewardIdList_.Add(other.challengeTakenRewardIdList_);
    challengeRaidList_.Add(other.challengeRaidList_);
    if (other.Retcode != 0) {
      Retcode = other.Retcode;
    }
    finishedRaidInfoList_.Add(other.finishedRaidInfoList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 26: {
          finishedRaidInfoList_.AddEntriesFrom(input, _repeated_finishedRaidInfoList_codec);
          break;
        }
        case 50: {
          challengeRaidList_.AddEntriesFrom(input, _repeated_challengeRaidList_codec);
          break;
        }
        case 90:
        case 88: {
          challengeTakenRewardIdList_.AddEntriesFrom(input, _repeated_challengeTakenRewardIdList_codec);
          break;
        }
        case 120: {
          Retcode = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 26: {
          finishedRaidInfoList_.AddEntriesFrom(ref input, _repeated_finishedRaidInfoList_codec);
          break;
        }
        case 50: {
          challengeRaidList_.AddEntriesFrom(ref input, _repeated_challengeRaidList_codec);
          break;
        }
        case 90:
        case 88: {
          challengeTakenRewardIdList_.AddEntriesFrom(ref input, _repeated_challengeTakenRewardIdList_codec);
          break;
        }
        case 120: {
          Retcode = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class FLMKEBIIGJO : pb::IMessage<FLMKEBIIGJO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FLMKEBIIGJO> _parser = new pb::MessageParser<FLMKEBIIGJO>(() => new FLMKEBIIGJO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FLMKEBIIGJO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetRaidInfoScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FLMKEBIIGJO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FLMKEBIIGJO(FLMKEBIIGJO other) : this() {
    currentRaidID_ = other.currentRaidID_;
    mNKBJDKMNFI_ = other.mNKBJDKMNFI_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FLMKEBIIGJO Clone() {
    return new FLMKEBIIGJO(this);
  }

  /// <summary>Field number for the "currentRaidID" field.</summary>
  public const int CurrentRaidIDFieldNumber = 9;
  private uint currentRaidID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CurrentRaidID {
    get { return currentRaidID_; }
    set {
      currentRaidID_ = value;
    }
  }

  /// <summary>Field number for the "mNKBJDKMNFI" field.</summary>
  public const int MNKBJDKMNFIFieldNumber = 4;
  private uint mNKBJDKMNFI_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MNKBJDKMNFI {
    get { return mNKBJDKMNFI_; }
    set {
      mNKBJDKMNFI_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FLMKEBIIGJO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FLMKEBIIGJO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CurrentRaidID != other.CurrentRaidID) return false;
    if (MNKBJDKMNFI != other.MNKBJDKMNFI) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CurrentRaidID != 0) hash ^= CurrentRaidID.GetHashCode();
    if (MNKBJDKMNFI != 0) hash ^= MNKBJDKMNFI.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MNKBJDKMNFI != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MNKBJDKMNFI);
    }
    if (CurrentRaidID != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(CurrentRaidID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MNKBJDKMNFI != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MNKBJDKMNFI);
    }
    if (CurrentRaidID != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(CurrentRaidID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CurrentRaidID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentRaidID);
    }
    if (MNKBJDKMNFI != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MNKBJDKMNFI);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FLMKEBIIGJO other) {
    if (other == null) {
      return;
    }
    if (other.CurrentRaidID != 0) {
      CurrentRaidID = other.CurrentRaidID;
    }
    if (other.MNKBJDKMNFI != 0) {
      MNKBJDKMNFI = other.MNKBJDKMNFI;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 32: {
          MNKBJDKMNFI = input.ReadUInt32();
          break;
        }
        case 72: {
          CurrentRaidID = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 32: {
          MNKBJDKMNFI = input.ReadUInt32();
          break;
        }
        case 72: {
          CurrentRaidID = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class OEIFMALECJD : pb::IMessage<OEIFMALECJD>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<OEIFMALECJD> _parser = new pb::MessageParser<OEIFMALECJD>(() => new OEIFMALECJD());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<OEIFMALECJD> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetRaidInfoScRspReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public OEIFMALECJD() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public OEIFMALECJD(OEIFMALECJD other) : this() {
    dMLLGNPMFPE_ = other.dMLLGNPMFPE_.Clone();
    worldLevel_ = other.worldLevel_;
    currentRaidID_ = other.currentRaidID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public OEIFMALECJD Clone() {
    return new OEIFMALECJD(this);
  }

  /// <summary>Field number for the "dMLLGNPMFPE" field.</summary>
  public const int DMLLGNPMFPEFieldNumber = 4;
  private static readonly pb::FieldCodec<uint> _repeated_dMLLGNPMFPE_codec
      = pb::FieldCodec.ForUInt32(34);
  private readonly pbc::RepeatedField<uint> dMLLGNPMFPE_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> DMLLGNPMFPE {
    get { return dMLLGNPMFPE_; }
  }

  /// <summary>Field number for the "worldLevel" field.</summary>
  public const int WorldLevelFieldNumber = 14;
  private uint worldLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint WorldLevel {
    get { return worldLevel_; }
    set {
      worldLevel_ = value;
    }
  }

  /// <summary>Field number for the "currentRaidID" field.</summary>
  public const int CurrentRaidIDFieldNumber = 8;
  private uint currentRaidID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CurrentRaidID {
    get { return currentRaidID_; }
    set {
      currentRaidID_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as OEIFMALECJD);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(OEIFMALECJD other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!dMLLGNPMFPE_.Equals(other.dMLLGNPMFPE_)) return false;
    if (WorldLevel != other.WorldLevel) return false;
    if (CurrentRaidID != other.CurrentRaidID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= dMLLGNPMFPE_.GetHashCode();
    if (WorldLevel != 0) hash ^= WorldLevel.GetHashCode();
    if (CurrentRaidID != 0) hash ^= CurrentRaidID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    dMLLGNPMFPE_.WriteTo(output, _repeated_dMLLGNPMFPE_codec);
    if (CurrentRaidID != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(CurrentRaidID);
    }
    if (WorldLevel != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(WorldLevel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    dMLLGNPMFPE_.WriteTo(ref output, _repeated_dMLLGNPMFPE_codec);
    if (CurrentRaidID != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(CurrentRaidID);
    }
    if (WorldLevel != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(WorldLevel);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += dMLLGNPMFPE_.CalculateSize(_repeated_dMLLGNPMFPE_codec);
    if (WorldLevel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WorldLevel);
    }
    if (CurrentRaidID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentRaidID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(OEIFMALECJD other) {
    if (other == null) {
      return;
    }
    dMLLGNPMFPE_.Add(other.dMLLGNPMFPE_);
    if (other.WorldLevel != 0) {
      WorldLevel = other.WorldLevel;
    }
    if (other.CurrentRaidID != 0) {
      CurrentRaidID = other.CurrentRaidID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 34:
        case 32: {
          dMLLGNPMFPE_.AddEntriesFrom(input, _repeated_dMLLGNPMFPE_codec);
          break;
        }
        case 64: {
          CurrentRaidID = input.ReadUInt32();
          break;
        }
        case 112: {
          WorldLevel = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 34:
        case 32: {
          dMLLGNPMFPE_.AddEntriesFrom(ref input, _repeated_dMLLGNPMFPE_codec);
          break;
        }
        case 64: {
          CurrentRaidID = input.ReadUInt32();
          break;
        }
        case 112: {
          WorldLevel = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
