// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UpdateFeatureSwitchScNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from UpdateFeatureSwitchScNotify.proto</summary>
public static partial class UpdateFeatureSwitchScNotifyReflection {

  #region Descriptor
  /// <summary>File descriptor for UpdateFeatureSwitchScNotify.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static UpdateFeatureSwitchScNotifyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiFVcGRhdGVGZWF0dXJlU3dpdGNoU2NOb3RpZnkucHJvdG8iSQobVXBkYXRl",
          "RmVhdHVyZVN3aXRjaFNjTm90aWZ5EioKDnN3aXRjaEluZm9MaXN0GA0gAygL",
          "MhIuRmVhdHVyZVN3aXRjaEluZm8ibAoRRmVhdHVyZVN3aXRjaEluZm8SIAoE",
          "dHlwZRgBIAEoDjISLkZlYXR1cmVTd2l0Y2hUeXBlEiAKCnN3aXRjaExpc3QY",
          "AiADKAsyDC5LR0xES05FSE9BRxITCgtpc0FsbENsb3NlZBgDIAEoCCIiCgtL",
          "R0xES05FSE9BRxITCgtkQkZQUEhNTkZGSRgBIAMoDSriBgoRRmVhdHVyZVN3",
          "aXRjaFR5cGUSFwoTRkVBVFVSRV9TV0lUQ0hfTk9ORRAAEhcKE0ZFQVRVUkVf",
          "U1dJVENIX1NIT1AQARIeChpGRUFUVVJFX1NXSVRDSF9MSU5FVVBfTkFNRRAC",
          "EiAKHEZFQVRVUkVfU1dJVENIX1JFQ0hBUkdFX1NIT1AQAxIbChdGRUFUVVJF",
          "X1NXSVRDSF9OSUNLTkFNRRAEEhwKGEZFQVRVUkVfU1dJVENIX1NJR05BVFVS",
          "RRAFEh0KGUZFQVRVUkVfU1dJVENIX0JBVFRMRVBBU1MQBhIcChhGRUFUVVJF",
          "X1NXSVRDSF9QVU5LX0xPUkQQBxIiCh5GRUFUVVJFX1NXSVRDSF9NT05USENB",
          "UkRfREFJTFkQCBIgChxGRUFUVVJFX1NXSVRDSF9QSUNUVVJFX1NIQVJFEAkS",
          "GAoURkVBVFVSRV9TV0lUQ0hfUk9HVUUQChIcChhGRUFUVVJFX1NXSVRDSF9D",
          "SEFMTEVOR0UQCxIZChVGRUFUVVJFX1NXSVRDSF9DT0NPT04QDBIXChNGRUFU",
          "VVJFX1NXSVRDSF9SQUlEEA0SIwofRkVBVFVSRV9TV0lUQ0hfTUFaRV9QTEFO",
          "RV9FVkVOVBAOEiEKHUZFQVRVUkVfU1dJVENIX0FDVElWSVRZX1BBTkVMEA8S",
          "GgoWRkVBVFVSRV9TV0lUQ0hfTUFJTEJPWBAQEhgKFEZFQVRVUkVfU1dJVENI",
          "X1FVRVNUEBESGAoURkVBVFVSRV9TV0lUQ0hfR0FDSEEQEhIXChNGRUFUVVJF",
          "X1NXSVRDSF9DSEFUEBMSJgoiRkVBVFVSRV9TV0lUQ0hfTU9ESUZZX0ZSSUVO",
          "RF9BTElBUxAUEhsKF0ZFQVRVUkVfU1dJVENIX1VTRV9JVEVNEBUSJAogRkVB",
          "VFVSRV9TV0lUQ0hfQUNUSVZJVFlfU0NIRURVTEUQFhIfChtGRUFUVVJFX1NX",
          "SVRDSF9GQVJNX0VMRU1FTlQQFxIkCiBGRUFUVVJFX1NXSVRDSF9BQ0hJRVZF",
          "TUVOVF9MRVZFTBAYEiUKIUZFQVRVUkVfU1dJVENIX0RBSUxZX0FDVElWRV9M",
          "RVZFTBAZEiUKIUZFQVRVUkVfU1dJVENIX0ZJUlNUX1NFVF9OSUNLTkFNRRAb",
          "YgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::FeatureSwitchType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::UpdateFeatureSwitchScNotify), global::UpdateFeatureSwitchScNotify.Parser, new[]{ "SwitchInfoList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FeatureSwitchInfo), global::FeatureSwitchInfo.Parser, new[]{ "Type", "SwitchList", "IsAllClosed" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::KGLDKNEHOAG), global::KGLDKNEHOAG.Parser, new[]{ "DBFPPHMNFFI" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum FeatureSwitchType {
  [pbr::OriginalName("FEATURE_SWITCH_NONE")] FeatureSwitchNone = 0,
  [pbr::OriginalName("FEATURE_SWITCH_SHOP")] FeatureSwitchShop = 1,
  [pbr::OriginalName("FEATURE_SWITCH_LINEUP_NAME")] FeatureSwitchLineupName = 2,
  [pbr::OriginalName("FEATURE_SWITCH_RECHARGE_SHOP")] FeatureSwitchRechargeShop = 3,
  [pbr::OriginalName("FEATURE_SWITCH_NICKNAME")] FeatureSwitchNickname = 4,
  [pbr::OriginalName("FEATURE_SWITCH_SIGNATURE")] FeatureSwitchSignature = 5,
  [pbr::OriginalName("FEATURE_SWITCH_BATTLEPASS")] FeatureSwitchBattlepass = 6,
  [pbr::OriginalName("FEATURE_SWITCH_PUNK_LORD")] FeatureSwitchPunkLord = 7,
  [pbr::OriginalName("FEATURE_SWITCH_MONTHCARD_DAILY")] FeatureSwitchMonthcardDaily = 8,
  [pbr::OriginalName("FEATURE_SWITCH_PICTURE_SHARE")] FeatureSwitchPictureShare = 9,
  [pbr::OriginalName("FEATURE_SWITCH_ROGUE")] FeatureSwitchRogue = 10,
  [pbr::OriginalName("FEATURE_SWITCH_CHALLENGE")] FeatureSwitchChallenge = 11,
  [pbr::OriginalName("FEATURE_SWITCH_COCOON")] FeatureSwitchCocoon = 12,
  [pbr::OriginalName("FEATURE_SWITCH_RAID")] FeatureSwitchRaid = 13,
  [pbr::OriginalName("FEATURE_SWITCH_MAZE_PLANE_EVENT")] FeatureSwitchMazePlaneEvent = 14,
  [pbr::OriginalName("FEATURE_SWITCH_ACTIVITY_PANEL")] FeatureSwitchActivityPanel = 15,
  [pbr::OriginalName("FEATURE_SWITCH_MAILBOX")] FeatureSwitchMailbox = 16,
  [pbr::OriginalName("FEATURE_SWITCH_QUEST")] FeatureSwitchQuest = 17,
  [pbr::OriginalName("FEATURE_SWITCH_GACHA")] FeatureSwitchGacha = 18,
  [pbr::OriginalName("FEATURE_SWITCH_CHAT")] FeatureSwitchChat = 19,
  [pbr::OriginalName("FEATURE_SWITCH_MODIFY_FRIEND_ALIAS")] FeatureSwitchModifyFriendAlias = 20,
  [pbr::OriginalName("FEATURE_SWITCH_USE_ITEM")] FeatureSwitchUseItem = 21,
  [pbr::OriginalName("FEATURE_SWITCH_ACTIVITY_SCHEDULE")] FeatureSwitchActivitySchedule = 22,
  [pbr::OriginalName("FEATURE_SWITCH_FARM_ELEMENT")] FeatureSwitchFarmElement = 23,
  [pbr::OriginalName("FEATURE_SWITCH_ACHIEVEMENT_LEVEL")] FeatureSwitchAchievementLevel = 24,
  [pbr::OriginalName("FEATURE_SWITCH_DAILY_ACTIVE_LEVEL")] FeatureSwitchDailyActiveLevel = 25,
  [pbr::OriginalName("FEATURE_SWITCH_FIRST_SET_NICKNAME")] FeatureSwitchFirstSetNickname = 27,
}

#endregion

#region Messages
public sealed partial class UpdateFeatureSwitchScNotify : pb::IMessage<UpdateFeatureSwitchScNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<UpdateFeatureSwitchScNotify> _parser = new pb::MessageParser<UpdateFeatureSwitchScNotify>(() => new UpdateFeatureSwitchScNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<UpdateFeatureSwitchScNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UpdateFeatureSwitchScNotifyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UpdateFeatureSwitchScNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UpdateFeatureSwitchScNotify(UpdateFeatureSwitchScNotify other) : this() {
    switchInfoList_ = other.switchInfoList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public UpdateFeatureSwitchScNotify Clone() {
    return new UpdateFeatureSwitchScNotify(this);
  }

  /// <summary>Field number for the "switchInfoList" field.</summary>
  public const int SwitchInfoListFieldNumber = 13;
  private static readonly pb::FieldCodec<global::FeatureSwitchInfo> _repeated_switchInfoList_codec
      = pb::FieldCodec.ForMessage(106, global::FeatureSwitchInfo.Parser);
  private readonly pbc::RepeatedField<global::FeatureSwitchInfo> switchInfoList_ = new pbc::RepeatedField<global::FeatureSwitchInfo>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::FeatureSwitchInfo> SwitchInfoList {
    get { return switchInfoList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as UpdateFeatureSwitchScNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(UpdateFeatureSwitchScNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!switchInfoList_.Equals(other.switchInfoList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= switchInfoList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    switchInfoList_.WriteTo(output, _repeated_switchInfoList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    switchInfoList_.WriteTo(ref output, _repeated_switchInfoList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += switchInfoList_.CalculateSize(_repeated_switchInfoList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(UpdateFeatureSwitchScNotify other) {
    if (other == null) {
      return;
    }
    switchInfoList_.Add(other.switchInfoList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 106: {
          switchInfoList_.AddEntriesFrom(input, _repeated_switchInfoList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 106: {
          switchInfoList_.AddEntriesFrom(ref input, _repeated_switchInfoList_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class FeatureSwitchInfo : pb::IMessage<FeatureSwitchInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FeatureSwitchInfo> _parser = new pb::MessageParser<FeatureSwitchInfo>(() => new FeatureSwitchInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FeatureSwitchInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UpdateFeatureSwitchScNotifyReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FeatureSwitchInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FeatureSwitchInfo(FeatureSwitchInfo other) : this() {
    type_ = other.type_;
    switchList_ = other.switchList_.Clone();
    isAllClosed_ = other.isAllClosed_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FeatureSwitchInfo Clone() {
    return new FeatureSwitchInfo(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::FeatureSwitchType type_ = global::FeatureSwitchType.FeatureSwitchNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FeatureSwitchType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "switchList" field.</summary>
  public const int SwitchListFieldNumber = 2;
  private static readonly pb::FieldCodec<global::KGLDKNEHOAG> _repeated_switchList_codec
      = pb::FieldCodec.ForMessage(18, global::KGLDKNEHOAG.Parser);
  private readonly pbc::RepeatedField<global::KGLDKNEHOAG> switchList_ = new pbc::RepeatedField<global::KGLDKNEHOAG>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::KGLDKNEHOAG> SwitchList {
    get { return switchList_; }
  }

  /// <summary>Field number for the "isAllClosed" field.</summary>
  public const int IsAllClosedFieldNumber = 3;
  private bool isAllClosed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsAllClosed {
    get { return isAllClosed_; }
    set {
      isAllClosed_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FeatureSwitchInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FeatureSwitchInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if(!switchList_.Equals(other.switchList_)) return false;
    if (IsAllClosed != other.IsAllClosed) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::FeatureSwitchType.FeatureSwitchNone) hash ^= Type.GetHashCode();
    hash ^= switchList_.GetHashCode();
    if (IsAllClosed != false) hash ^= IsAllClosed.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::FeatureSwitchType.FeatureSwitchNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    switchList_.WriteTo(output, _repeated_switchList_codec);
    if (IsAllClosed != false) {
      output.WriteRawTag(24);
      output.WriteBool(IsAllClosed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::FeatureSwitchType.FeatureSwitchNone) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    switchList_.WriteTo(ref output, _repeated_switchList_codec);
    if (IsAllClosed != false) {
      output.WriteRawTag(24);
      output.WriteBool(IsAllClosed);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::FeatureSwitchType.FeatureSwitchNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    size += switchList_.CalculateSize(_repeated_switchList_codec);
    if (IsAllClosed != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FeatureSwitchInfo other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::FeatureSwitchType.FeatureSwitchNone) {
      Type = other.Type;
    }
    switchList_.Add(other.switchList_);
    if (other.IsAllClosed != false) {
      IsAllClosed = other.IsAllClosed;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::FeatureSwitchType) input.ReadEnum();
          break;
        }
        case 18: {
          switchList_.AddEntriesFrom(input, _repeated_switchList_codec);
          break;
        }
        case 24: {
          IsAllClosed = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::FeatureSwitchType) input.ReadEnum();
          break;
        }
        case 18: {
          switchList_.AddEntriesFrom(ref input, _repeated_switchList_codec);
          break;
        }
        case 24: {
          IsAllClosed = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class KGLDKNEHOAG : pb::IMessage<KGLDKNEHOAG>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<KGLDKNEHOAG> _parser = new pb::MessageParser<KGLDKNEHOAG>(() => new KGLDKNEHOAG());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<KGLDKNEHOAG> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::UpdateFeatureSwitchScNotifyReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KGLDKNEHOAG() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KGLDKNEHOAG(KGLDKNEHOAG other) : this() {
    dBFPPHMNFFI_ = other.dBFPPHMNFFI_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public KGLDKNEHOAG Clone() {
    return new KGLDKNEHOAG(this);
  }

  /// <summary>Field number for the "dBFPPHMNFFI" field.</summary>
  public const int DBFPPHMNFFIFieldNumber = 1;
  private static readonly pb::FieldCodec<uint> _repeated_dBFPPHMNFFI_codec
      = pb::FieldCodec.ForUInt32(10);
  private readonly pbc::RepeatedField<uint> dBFPPHMNFFI_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> DBFPPHMNFFI {
    get { return dBFPPHMNFFI_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as KGLDKNEHOAG);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(KGLDKNEHOAG other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!dBFPPHMNFFI_.Equals(other.dBFPPHMNFFI_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= dBFPPHMNFFI_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    dBFPPHMNFFI_.WriteTo(output, _repeated_dBFPPHMNFFI_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    dBFPPHMNFFI_.WriteTo(ref output, _repeated_dBFPPHMNFFI_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += dBFPPHMNFFI_.CalculateSize(_repeated_dBFPPHMNFFI_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(KGLDKNEHOAG other) {
    if (other == null) {
      return;
    }
    dBFPPHMNFFI_.Add(other.dBFPPHMNFFI_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          dBFPPHMNFFI_.AddEntriesFrom(input, _repeated_dBFPPHMNFFI_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 8: {
          dBFPPHMNFFI_.AddEntriesFrom(ref input, _repeated_dBFPPHMNFFI_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
