// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetBoxingClubInfoScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetBoxingClubInfoScRsp.proto</summary>
public static partial class GetBoxingClubInfoScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetBoxingClubInfoScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetBoxingClubInfoScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxHZXRCb3hpbmdDbHViSW5mb1NjUnNwLnByb3RvIkwKFkdldEJveGluZ0Ns",
          "dWJJbmZvU2NSc3ASIQoLZEZERUJPTUNOSk4YBCADKAsyDC5NQUxGSUFOTkpH",
          "UBIPCgdtX3ZhbHVlGAIgASgNItQBCgtNQUxGSUFOTkpHUBIZChFjdXJyZW50",
          "U3RhZ2VJbmRleBgNIAEoDRITCgtqQVBBRU5EQ0ZDTBgIIAEoDRIXCg9jdXJy",
          "ZW50Um91bmROdW0YCiABKA0SEwoLbkxEREZKQ0FISUEYAyADKA0SFgoOaGFz",
          "VGFrZW5SZXdhcmQYCSABKAgSIQoLZkpLTU5FT0pORk0YBiADKAsyDC5DQk1D",
          "TEJMRklNShIXCg9iZXN0Um91bmRSZWNvcmQYASABKA0SEwoLY2hhbGxlbmdl",
          "SUQYCyABKA0iRwoLQ0JNQ0xCTEZJTUoSKAoTY2hhcmFjdGVyQXZhdGFyVHlw",
          "ZRgGIAEoDjILLkF2YXRhclR5cGUSDgoGcmVhbElEGA8gASgNKoABCgpBdmF0",
          "YXJUeXBlEhQKEEFWQVRBUl9UWVBFX05PTkUQABIVChFBVkFUQVJfVFJJQUxf",
          "VFlQRRABEhUKEUFWQVRBUl9MSU1JVF9UWVBFEAISFgoSQVZBVEFSX0ZPUk1B",
          "TF9UWVBFEAMSFgoSQVZBVEFSX0FTU0lTVF9UWVBFEARiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::AvatarType), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetBoxingClubInfoScRsp), global::GetBoxingClubInfoScRsp.Parser, new[]{ "DFDEBOMCNJN", "MValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MALFIANNJGP), global::MALFIANNJGP.Parser, new[]{ "CurrentStageIndex", "JAPAENDCFCL", "CurrentRoundNum", "NLDDFJCAHIA", "HasTakenReward", "FJKMNEOJNFM", "BestRoundRecord", "ChallengeID" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CBMCLBLFIMJ), global::CBMCLBLFIMJ.Parser, new[]{ "CharacterAvatarType", "RealID" }, null, null, null, null)
        }));
  }
  #endregion

}

#region Messages
public sealed partial class GetBoxingClubInfoScRsp : pb::IMessage<GetBoxingClubInfoScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetBoxingClubInfoScRsp> _parser = new pb::MessageParser<GetBoxingClubInfoScRsp>(() => new GetBoxingClubInfoScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetBoxingClubInfoScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetBoxingClubInfoScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetBoxingClubInfoScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetBoxingClubInfoScRsp(GetBoxingClubInfoScRsp other) : this() {
    dFDEBOMCNJN_ = other.dFDEBOMCNJN_.Clone();
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetBoxingClubInfoScRsp Clone() {
    return new GetBoxingClubInfoScRsp(this);
  }

  /// <summary>Field number for the "dFDEBOMCNJN" field.</summary>
  public const int DFDEBOMCNJNFieldNumber = 4;
  private static readonly pb::FieldCodec<global::MALFIANNJGP> _repeated_dFDEBOMCNJN_codec
      = pb::FieldCodec.ForMessage(34, global::MALFIANNJGP.Parser);
  private readonly pbc::RepeatedField<global::MALFIANNJGP> dFDEBOMCNJN_ = new pbc::RepeatedField<global::MALFIANNJGP>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::MALFIANNJGP> DFDEBOMCNJN {
    get { return dFDEBOMCNJN_; }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 2;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetBoxingClubInfoScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetBoxingClubInfoScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!dFDEBOMCNJN_.Equals(other.dFDEBOMCNJN_)) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= dFDEBOMCNJN_.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MValue != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(MValue);
    }
    dFDEBOMCNJN_.WriteTo(output, _repeated_dFDEBOMCNJN_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MValue != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(MValue);
    }
    dFDEBOMCNJN_.WriteTo(ref output, _repeated_dFDEBOMCNJN_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += dFDEBOMCNJN_.CalculateSize(_repeated_dFDEBOMCNJN_codec);
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetBoxingClubInfoScRsp other) {
    if (other == null) {
      return;
    }
    dFDEBOMCNJN_.Add(other.dFDEBOMCNJN_);
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          MValue = input.ReadUInt32();
          break;
        }
        case 34: {
          dFDEBOMCNJN_.AddEntriesFrom(input, _repeated_dFDEBOMCNJN_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          MValue = input.ReadUInt32();
          break;
        }
        case 34: {
          dFDEBOMCNJN_.AddEntriesFrom(ref input, _repeated_dFDEBOMCNJN_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class MALFIANNJGP : pb::IMessage<MALFIANNJGP>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MALFIANNJGP> _parser = new pb::MessageParser<MALFIANNJGP>(() => new MALFIANNJGP());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MALFIANNJGP> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetBoxingClubInfoScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MALFIANNJGP() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MALFIANNJGP(MALFIANNJGP other) : this() {
    currentStageIndex_ = other.currentStageIndex_;
    jAPAENDCFCL_ = other.jAPAENDCFCL_;
    currentRoundNum_ = other.currentRoundNum_;
    nLDDFJCAHIA_ = other.nLDDFJCAHIA_.Clone();
    hasTakenReward_ = other.hasTakenReward_;
    fJKMNEOJNFM_ = other.fJKMNEOJNFM_.Clone();
    bestRoundRecord_ = other.bestRoundRecord_;
    challengeID_ = other.challengeID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MALFIANNJGP Clone() {
    return new MALFIANNJGP(this);
  }

  /// <summary>Field number for the "currentStageIndex" field.</summary>
  public const int CurrentStageIndexFieldNumber = 13;
  private uint currentStageIndex_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CurrentStageIndex {
    get { return currentStageIndex_; }
    set {
      currentStageIndex_ = value;
    }
  }

  /// <summary>Field number for the "jAPAENDCFCL" field.</summary>
  public const int JAPAENDCFCLFieldNumber = 8;
  private uint jAPAENDCFCL_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint JAPAENDCFCL {
    get { return jAPAENDCFCL_; }
    set {
      jAPAENDCFCL_ = value;
    }
  }

  /// <summary>Field number for the "currentRoundNum" field.</summary>
  public const int CurrentRoundNumFieldNumber = 10;
  private uint currentRoundNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CurrentRoundNum {
    get { return currentRoundNum_; }
    set {
      currentRoundNum_ = value;
    }
  }

  /// <summary>Field number for the "nLDDFJCAHIA" field.</summary>
  public const int NLDDFJCAHIAFieldNumber = 3;
  private static readonly pb::FieldCodec<uint> _repeated_nLDDFJCAHIA_codec
      = pb::FieldCodec.ForUInt32(26);
  private readonly pbc::RepeatedField<uint> nLDDFJCAHIA_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> NLDDFJCAHIA {
    get { return nLDDFJCAHIA_; }
  }

  /// <summary>Field number for the "hasTakenReward" field.</summary>
  public const int HasTakenRewardFieldNumber = 9;
  private bool hasTakenReward_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTakenReward {
    get { return hasTakenReward_; }
    set {
      hasTakenReward_ = value;
    }
  }

  /// <summary>Field number for the "fJKMNEOJNFM" field.</summary>
  public const int FJKMNEOJNFMFieldNumber = 6;
  private static readonly pb::FieldCodec<global::CBMCLBLFIMJ> _repeated_fJKMNEOJNFM_codec
      = pb::FieldCodec.ForMessage(50, global::CBMCLBLFIMJ.Parser);
  private readonly pbc::RepeatedField<global::CBMCLBLFIMJ> fJKMNEOJNFM_ = new pbc::RepeatedField<global::CBMCLBLFIMJ>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CBMCLBLFIMJ> FJKMNEOJNFM {
    get { return fJKMNEOJNFM_; }
  }

  /// <summary>Field number for the "bestRoundRecord" field.</summary>
  public const int BestRoundRecordFieldNumber = 1;
  private uint bestRoundRecord_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint BestRoundRecord {
    get { return bestRoundRecord_; }
    set {
      bestRoundRecord_ = value;
    }
  }

  /// <summary>Field number for the "challengeID" field.</summary>
  public const int ChallengeIDFieldNumber = 11;
  private uint challengeID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ChallengeID {
    get { return challengeID_; }
    set {
      challengeID_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MALFIANNJGP);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MALFIANNJGP other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CurrentStageIndex != other.CurrentStageIndex) return false;
    if (JAPAENDCFCL != other.JAPAENDCFCL) return false;
    if (CurrentRoundNum != other.CurrentRoundNum) return false;
    if(!nLDDFJCAHIA_.Equals(other.nLDDFJCAHIA_)) return false;
    if (HasTakenReward != other.HasTakenReward) return false;
    if(!fJKMNEOJNFM_.Equals(other.fJKMNEOJNFM_)) return false;
    if (BestRoundRecord != other.BestRoundRecord) return false;
    if (ChallengeID != other.ChallengeID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CurrentStageIndex != 0) hash ^= CurrentStageIndex.GetHashCode();
    if (JAPAENDCFCL != 0) hash ^= JAPAENDCFCL.GetHashCode();
    if (CurrentRoundNum != 0) hash ^= CurrentRoundNum.GetHashCode();
    hash ^= nLDDFJCAHIA_.GetHashCode();
    if (HasTakenReward != false) hash ^= HasTakenReward.GetHashCode();
    hash ^= fJKMNEOJNFM_.GetHashCode();
    if (BestRoundRecord != 0) hash ^= BestRoundRecord.GetHashCode();
    if (ChallengeID != 0) hash ^= ChallengeID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (BestRoundRecord != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(BestRoundRecord);
    }
    nLDDFJCAHIA_.WriteTo(output, _repeated_nLDDFJCAHIA_codec);
    fJKMNEOJNFM_.WriteTo(output, _repeated_fJKMNEOJNFM_codec);
    if (JAPAENDCFCL != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(JAPAENDCFCL);
    }
    if (HasTakenReward != false) {
      output.WriteRawTag(72);
      output.WriteBool(HasTakenReward);
    }
    if (CurrentRoundNum != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(CurrentRoundNum);
    }
    if (ChallengeID != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(ChallengeID);
    }
    if (CurrentStageIndex != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(CurrentStageIndex);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (BestRoundRecord != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(BestRoundRecord);
    }
    nLDDFJCAHIA_.WriteTo(ref output, _repeated_nLDDFJCAHIA_codec);
    fJKMNEOJNFM_.WriteTo(ref output, _repeated_fJKMNEOJNFM_codec);
    if (JAPAENDCFCL != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(JAPAENDCFCL);
    }
    if (HasTakenReward != false) {
      output.WriteRawTag(72);
      output.WriteBool(HasTakenReward);
    }
    if (CurrentRoundNum != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(CurrentRoundNum);
    }
    if (ChallengeID != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(ChallengeID);
    }
    if (CurrentStageIndex != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(CurrentStageIndex);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CurrentStageIndex != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentStageIndex);
    }
    if (JAPAENDCFCL != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JAPAENDCFCL);
    }
    if (CurrentRoundNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentRoundNum);
    }
    size += nLDDFJCAHIA_.CalculateSize(_repeated_nLDDFJCAHIA_codec);
    if (HasTakenReward != false) {
      size += 1 + 1;
    }
    size += fJKMNEOJNFM_.CalculateSize(_repeated_fJKMNEOJNFM_codec);
    if (BestRoundRecord != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BestRoundRecord);
    }
    if (ChallengeID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChallengeID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MALFIANNJGP other) {
    if (other == null) {
      return;
    }
    if (other.CurrentStageIndex != 0) {
      CurrentStageIndex = other.CurrentStageIndex;
    }
    if (other.JAPAENDCFCL != 0) {
      JAPAENDCFCL = other.JAPAENDCFCL;
    }
    if (other.CurrentRoundNum != 0) {
      CurrentRoundNum = other.CurrentRoundNum;
    }
    nLDDFJCAHIA_.Add(other.nLDDFJCAHIA_);
    if (other.HasTakenReward != false) {
      HasTakenReward = other.HasTakenReward;
    }
    fJKMNEOJNFM_.Add(other.fJKMNEOJNFM_);
    if (other.BestRoundRecord != 0) {
      BestRoundRecord = other.BestRoundRecord;
    }
    if (other.ChallengeID != 0) {
      ChallengeID = other.ChallengeID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          BestRoundRecord = input.ReadUInt32();
          break;
        }
        case 26:
        case 24: {
          nLDDFJCAHIA_.AddEntriesFrom(input, _repeated_nLDDFJCAHIA_codec);
          break;
        }
        case 50: {
          fJKMNEOJNFM_.AddEntriesFrom(input, _repeated_fJKMNEOJNFM_codec);
          break;
        }
        case 64: {
          JAPAENDCFCL = input.ReadUInt32();
          break;
        }
        case 72: {
          HasTakenReward = input.ReadBool();
          break;
        }
        case 80: {
          CurrentRoundNum = input.ReadUInt32();
          break;
        }
        case 88: {
          ChallengeID = input.ReadUInt32();
          break;
        }
        case 104: {
          CurrentStageIndex = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          BestRoundRecord = input.ReadUInt32();
          break;
        }
        case 26:
        case 24: {
          nLDDFJCAHIA_.AddEntriesFrom(ref input, _repeated_nLDDFJCAHIA_codec);
          break;
        }
        case 50: {
          fJKMNEOJNFM_.AddEntriesFrom(ref input, _repeated_fJKMNEOJNFM_codec);
          break;
        }
        case 64: {
          JAPAENDCFCL = input.ReadUInt32();
          break;
        }
        case 72: {
          HasTakenReward = input.ReadBool();
          break;
        }
        case 80: {
          CurrentRoundNum = input.ReadUInt32();
          break;
        }
        case 88: {
          ChallengeID = input.ReadUInt32();
          break;
        }
        case 104: {
          CurrentStageIndex = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class CBMCLBLFIMJ : pb::IMessage<CBMCLBLFIMJ>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CBMCLBLFIMJ> _parser = new pb::MessageParser<CBMCLBLFIMJ>(() => new CBMCLBLFIMJ());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CBMCLBLFIMJ> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetBoxingClubInfoScRspReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CBMCLBLFIMJ() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CBMCLBLFIMJ(CBMCLBLFIMJ other) : this() {
    characterAvatarType_ = other.characterAvatarType_;
    realID_ = other.realID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CBMCLBLFIMJ Clone() {
    return new CBMCLBLFIMJ(this);
  }

  /// <summary>Field number for the "characterAvatarType" field.</summary>
  public const int CharacterAvatarTypeFieldNumber = 6;
  private global::AvatarType characterAvatarType_ = global::AvatarType.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AvatarType CharacterAvatarType {
    get { return characterAvatarType_; }
    set {
      characterAvatarType_ = value;
    }
  }

  /// <summary>Field number for the "realID" field.</summary>
  public const int RealIDFieldNumber = 15;
  private uint realID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RealID {
    get { return realID_; }
    set {
      realID_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CBMCLBLFIMJ);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CBMCLBLFIMJ other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (CharacterAvatarType != other.CharacterAvatarType) return false;
    if (RealID != other.RealID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (CharacterAvatarType != global::AvatarType.None) hash ^= CharacterAvatarType.GetHashCode();
    if (RealID != 0) hash ^= RealID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (CharacterAvatarType != global::AvatarType.None) {
      output.WriteRawTag(48);
      output.WriteEnum((int) CharacterAvatarType);
    }
    if (RealID != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(RealID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (CharacterAvatarType != global::AvatarType.None) {
      output.WriteRawTag(48);
      output.WriteEnum((int) CharacterAvatarType);
    }
    if (RealID != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(RealID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (CharacterAvatarType != global::AvatarType.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CharacterAvatarType);
    }
    if (RealID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RealID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CBMCLBLFIMJ other) {
    if (other == null) {
      return;
    }
    if (other.CharacterAvatarType != global::AvatarType.None) {
      CharacterAvatarType = other.CharacterAvatarType;
    }
    if (other.RealID != 0) {
      RealID = other.RealID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 48: {
          CharacterAvatarType = (global::AvatarType) input.ReadEnum();
          break;
        }
        case 120: {
          RealID = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 48: {
          CharacterAvatarType = (global::AvatarType) input.ReadEnum();
          break;
        }
        case 120: {
          RealID = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
