// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetLoginActivityScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetLoginActivityScRsp.proto</summary>
public static partial class GetLoginActivityScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetLoginActivityScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetLoginActivityScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtHZXRMb2dpbkFjdGl2aXR5U2NSc3AucHJvdG8iSwoVR2V0TG9naW5BY3Rp",
          "dml0eVNjUnNwEiEKC3BHTkxMSUJEREJHGAQgAygLMgwuSkFOQktITlBFSEgS",
          "DwoHbV92YWx1ZRgFIAEoDSJCCgtKQU5CS0hOUEVISBIKCgJpZBgCIAEoDRIT",
          "CgtpSEZNTUJEQkZIThgFIAMoDRISCgpfTG9naW5EYXlzGAsgASgNYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetLoginActivityScRsp), global::GetLoginActivityScRsp.Parser, new[]{ "PGNLLIBDDBG", "MValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::JANBKHNPEHH), global::JANBKHNPEHH.Parser, new[]{ "Id", "IHFMMBDBFHN", "LoginDays" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetLoginActivityScRsp : pb::IMessage<GetLoginActivityScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetLoginActivityScRsp> _parser = new pb::MessageParser<GetLoginActivityScRsp>(() => new GetLoginActivityScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetLoginActivityScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetLoginActivityScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetLoginActivityScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetLoginActivityScRsp(GetLoginActivityScRsp other) : this() {
    pGNLLIBDDBG_ = other.pGNLLIBDDBG_.Clone();
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetLoginActivityScRsp Clone() {
    return new GetLoginActivityScRsp(this);
  }

  /// <summary>Field number for the "pGNLLIBDDBG" field.</summary>
  public const int PGNLLIBDDBGFieldNumber = 4;
  private static readonly pb::FieldCodec<global::JANBKHNPEHH> _repeated_pGNLLIBDDBG_codec
      = pb::FieldCodec.ForMessage(34, global::JANBKHNPEHH.Parser);
  private readonly pbc::RepeatedField<global::JANBKHNPEHH> pGNLLIBDDBG_ = new pbc::RepeatedField<global::JANBKHNPEHH>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::JANBKHNPEHH> PGNLLIBDDBG {
    get { return pGNLLIBDDBG_; }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 5;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetLoginActivityScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetLoginActivityScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!pGNLLIBDDBG_.Equals(other.pGNLLIBDDBG_)) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= pGNLLIBDDBG_.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    pGNLLIBDDBG_.WriteTo(output, _repeated_pGNLLIBDDBG_codec);
    if (MValue != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(MValue);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    pGNLLIBDDBG_.WriteTo(ref output, _repeated_pGNLLIBDDBG_codec);
    if (MValue != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(MValue);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += pGNLLIBDDBG_.CalculateSize(_repeated_pGNLLIBDDBG_codec);
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetLoginActivityScRsp other) {
    if (other == null) {
      return;
    }
    pGNLLIBDDBG_.Add(other.pGNLLIBDDBG_);
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 34: {
          pGNLLIBDDBG_.AddEntriesFrom(input, _repeated_pGNLLIBDDBG_codec);
          break;
        }
        case 40: {
          MValue = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 34: {
          pGNLLIBDDBG_.AddEntriesFrom(ref input, _repeated_pGNLLIBDDBG_codec);
          break;
        }
        case 40: {
          MValue = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class JANBKHNPEHH : pb::IMessage<JANBKHNPEHH>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<JANBKHNPEHH> _parser = new pb::MessageParser<JANBKHNPEHH>(() => new JANBKHNPEHH());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<JANBKHNPEHH> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetLoginActivityScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JANBKHNPEHH() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JANBKHNPEHH(JANBKHNPEHH other) : this() {
    id_ = other.id_;
    iHFMMBDBFHN_ = other.iHFMMBDBFHN_.Clone();
    LoginDays_ = other.LoginDays_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public JANBKHNPEHH Clone() {
    return new JANBKHNPEHH(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 2;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "iHFMMBDBFHN" field.</summary>
  public const int IHFMMBDBFHNFieldNumber = 5;
  private static readonly pb::FieldCodec<uint> _repeated_iHFMMBDBFHN_codec
      = pb::FieldCodec.ForUInt32(42);
  private readonly pbc::RepeatedField<uint> iHFMMBDBFHN_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> IHFMMBDBFHN {
    get { return iHFMMBDBFHN_; }
  }

  /// <summary>Field number for the "_LoginDays" field.</summary>
  public const int LoginDaysFieldNumber = 11;
  private uint LoginDays_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint LoginDays {
    get { return LoginDays_; }
    set {
      LoginDays_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as JANBKHNPEHH);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(JANBKHNPEHH other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if(!iHFMMBDBFHN_.Equals(other.iHFMMBDBFHN_)) return false;
    if (LoginDays != other.LoginDays) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    hash ^= iHFMMBDBFHN_.GetHashCode();
    if (LoginDays != 0) hash ^= LoginDays.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Id);
    }
    iHFMMBDBFHN_.WriteTo(output, _repeated_iHFMMBDBFHN_codec);
    if (LoginDays != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(LoginDays);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Id);
    }
    iHFMMBDBFHN_.WriteTo(ref output, _repeated_iHFMMBDBFHN_codec);
    if (LoginDays != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(LoginDays);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    size += iHFMMBDBFHN_.CalculateSize(_repeated_iHFMMBDBFHN_codec);
    if (LoginDays != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LoginDays);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(JANBKHNPEHH other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    iHFMMBDBFHN_.Add(other.iHFMMBDBFHN_);
    if (other.LoginDays != 0) {
      LoginDays = other.LoginDays;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          Id = input.ReadUInt32();
          break;
        }
        case 42:
        case 40: {
          iHFMMBDBFHN_.AddEntriesFrom(input, _repeated_iHFMMBDBFHN_codec);
          break;
        }
        case 88: {
          LoginDays = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          Id = input.ReadUInt32();
          break;
        }
        case 42:
        case 40: {
          iHFMMBDBFHN_.AddEntriesFrom(ref input, _repeated_iHFMMBDBFHN_codec);
          break;
        }
        case 88: {
          LoginDays = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
