// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetTrialActivityDataScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetTrialActivityDataScRsp.proto</summary>
public static partial class GetTrialActivityDataScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetTrialActivityDataScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetTrialActivityDataScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch9HZXRUcmlhbEFjdGl2aXR5RGF0YVNjUnNwLnByb3RvIk8KGUdldFRyaWFs",
          "QWN0aXZpdHlEYXRhU2NSc3ASIQoLbVBLREFQT0NFREMYASADKAsyDC5MR0NQ",
          "SkpMS09OTBIPCgdtX3ZhbHVlGAMgASgNIjMKC0xHQ1BKSkxLT05MEhMKC2JK",
          "Qk9KQ0lLSUtEGA8gASgIEg8KB3N0YWdlSUQYDSABKA1iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetTrialActivityDataScRsp), global::GetTrialActivityDataScRsp.Parser, new[]{ "MPKDAPOCEDC", "MValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LGCPJJLKONL), global::LGCPJJLKONL.Parser, new[]{ "BJBOJCIKIKD", "StageID" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetTrialActivityDataScRsp : pb::IMessage<GetTrialActivityDataScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetTrialActivityDataScRsp> _parser = new pb::MessageParser<GetTrialActivityDataScRsp>(() => new GetTrialActivityDataScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetTrialActivityDataScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetTrialActivityDataScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetTrialActivityDataScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetTrialActivityDataScRsp(GetTrialActivityDataScRsp other) : this() {
    mPKDAPOCEDC_ = other.mPKDAPOCEDC_.Clone();
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetTrialActivityDataScRsp Clone() {
    return new GetTrialActivityDataScRsp(this);
  }

  /// <summary>Field number for the "mPKDAPOCEDC" field.</summary>
  public const int MPKDAPOCEDCFieldNumber = 1;
  private static readonly pb::FieldCodec<global::LGCPJJLKONL> _repeated_mPKDAPOCEDC_codec
      = pb::FieldCodec.ForMessage(10, global::LGCPJJLKONL.Parser);
  private readonly pbc::RepeatedField<global::LGCPJJLKONL> mPKDAPOCEDC_ = new pbc::RepeatedField<global::LGCPJJLKONL>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::LGCPJJLKONL> MPKDAPOCEDC {
    get { return mPKDAPOCEDC_; }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 3;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetTrialActivityDataScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetTrialActivityDataScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!mPKDAPOCEDC_.Equals(other.mPKDAPOCEDC_)) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= mPKDAPOCEDC_.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    mPKDAPOCEDC_.WriteTo(output, _repeated_mPKDAPOCEDC_codec);
    if (MValue != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(MValue);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    mPKDAPOCEDC_.WriteTo(ref output, _repeated_mPKDAPOCEDC_codec);
    if (MValue != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(MValue);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += mPKDAPOCEDC_.CalculateSize(_repeated_mPKDAPOCEDC_codec);
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetTrialActivityDataScRsp other) {
    if (other == null) {
      return;
    }
    mPKDAPOCEDC_.Add(other.mPKDAPOCEDC_);
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          mPKDAPOCEDC_.AddEntriesFrom(input, _repeated_mPKDAPOCEDC_codec);
          break;
        }
        case 24: {
          MValue = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          mPKDAPOCEDC_.AddEntriesFrom(ref input, _repeated_mPKDAPOCEDC_codec);
          break;
        }
        case 24: {
          MValue = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LGCPJJLKONL : pb::IMessage<LGCPJJLKONL>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LGCPJJLKONL> _parser = new pb::MessageParser<LGCPJJLKONL>(() => new LGCPJJLKONL());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LGCPJJLKONL> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetTrialActivityDataScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LGCPJJLKONL() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LGCPJJLKONL(LGCPJJLKONL other) : this() {
    bJBOJCIKIKD_ = other.bJBOJCIKIKD_;
    stageID_ = other.stageID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LGCPJJLKONL Clone() {
    return new LGCPJJLKONL(this);
  }

  /// <summary>Field number for the "bJBOJCIKIKD" field.</summary>
  public const int BJBOJCIKIKDFieldNumber = 15;
  private bool bJBOJCIKIKD_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool BJBOJCIKIKD {
    get { return bJBOJCIKIKD_; }
    set {
      bJBOJCIKIKD_ = value;
    }
  }

  /// <summary>Field number for the "stageID" field.</summary>
  public const int StageIDFieldNumber = 13;
  private uint stageID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint StageID {
    get { return stageID_; }
    set {
      stageID_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LGCPJJLKONL);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LGCPJJLKONL other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (BJBOJCIKIKD != other.BJBOJCIKIKD) return false;
    if (StageID != other.StageID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (BJBOJCIKIKD != false) hash ^= BJBOJCIKIKD.GetHashCode();
    if (StageID != 0) hash ^= StageID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (StageID != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(StageID);
    }
    if (BJBOJCIKIKD != false) {
      output.WriteRawTag(120);
      output.WriteBool(BJBOJCIKIKD);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (StageID != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(StageID);
    }
    if (BJBOJCIKIKD != false) {
      output.WriteRawTag(120);
      output.WriteBool(BJBOJCIKIKD);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (BJBOJCIKIKD != false) {
      size += 1 + 1;
    }
    if (StageID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StageID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LGCPJJLKONL other) {
    if (other == null) {
      return;
    }
    if (other.BJBOJCIKIKD != false) {
      BJBOJCIKIKD = other.BJBOJCIKIKD;
    }
    if (other.StageID != 0) {
      StageID = other.StageID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 104: {
          StageID = input.ReadUInt32();
          break;
        }
        case 120: {
          BJBOJCIKIKD = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 104: {
          StageID = input.ReadUInt32();
          break;
        }
        case 120: {
          BJBOJCIKIKD = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
