// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerKickoutScNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PlayerKickoutScNotify.proto</summary>
public static partial class PlayerKickoutScNotifyReflection {

  #region Descriptor
  /// <summary>File descriptor for PlayerKickoutScNotify.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerKickoutScNotifyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtQbGF5ZXJLaWNrb3V0U2NOb3RpZnkucHJvdG8iOgoVUGxheWVyS2lja291",
          "dFNjTm90aWZ5EiEKC0pJT0tNSERPUEpQGAkgASgLMgwuRUdISEpESEhCS00i",
          "YQoLRUdISEpESEhCS00SEwoLS0pIRENFREpBQ04YASABKAMSEwoLRkNPTk9G",
          "RUtKTUgYAiABKAMSEwoLQU1LQU1DQ1BHSEgYAyABKA0SEwoLRkdOTUpEREdI",
          "TkEYBCABKA1iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerKickoutScNotify), global::PlayerKickoutScNotify.Parser, new[]{ "JIOKMHDOPJP" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EGHHJDHHBKM), global::EGHHJDHHBKM.Parser, new[]{ "KJHDCEDJACN", "FCONOFEKJMH", "AMKAMCCPGHH", "FGNMJDDGHNA" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PlayerKickoutScNotify : pb::IMessage<PlayerKickoutScNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerKickoutScNotify> _parser = new pb::MessageParser<PlayerKickoutScNotify>(() => new PlayerKickoutScNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerKickoutScNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerKickoutScNotifyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerKickoutScNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerKickoutScNotify(PlayerKickoutScNotify other) : this() {
    jIOKMHDOPJP_ = other.jIOKMHDOPJP_ != null ? other.jIOKMHDOPJP_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerKickoutScNotify Clone() {
    return new PlayerKickoutScNotify(this);
  }

  /// <summary>Field number for the "JIOKMHDOPJP" field.</summary>
  public const int JIOKMHDOPJPFieldNumber = 9;
  private global::EGHHJDHHBKM jIOKMHDOPJP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::EGHHJDHHBKM JIOKMHDOPJP {
    get { return jIOKMHDOPJP_; }
    set {
      jIOKMHDOPJP_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerKickoutScNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerKickoutScNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(JIOKMHDOPJP, other.JIOKMHDOPJP)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (jIOKMHDOPJP_ != null) hash ^= JIOKMHDOPJP.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (jIOKMHDOPJP_ != null) {
      output.WriteRawTag(74);
      output.WriteMessage(JIOKMHDOPJP);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (jIOKMHDOPJP_ != null) {
      output.WriteRawTag(74);
      output.WriteMessage(JIOKMHDOPJP);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (jIOKMHDOPJP_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(JIOKMHDOPJP);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerKickoutScNotify other) {
    if (other == null) {
      return;
    }
    if (other.jIOKMHDOPJP_ != null) {
      if (jIOKMHDOPJP_ == null) {
        JIOKMHDOPJP = new global::EGHHJDHHBKM();
      }
      JIOKMHDOPJP.MergeFrom(other.JIOKMHDOPJP);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 74: {
          if (jIOKMHDOPJP_ == null) {
            JIOKMHDOPJP = new global::EGHHJDHHBKM();
          }
          input.ReadMessage(JIOKMHDOPJP);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 74: {
          if (jIOKMHDOPJP_ == null) {
            JIOKMHDOPJP = new global::EGHHJDHHBKM();
          }
          input.ReadMessage(JIOKMHDOPJP);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class EGHHJDHHBKM : pb::IMessage<EGHHJDHHBKM>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EGHHJDHHBKM> _parser = new pb::MessageParser<EGHHJDHHBKM>(() => new EGHHJDHHBKM());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EGHHJDHHBKM> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerKickoutScNotifyReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EGHHJDHHBKM() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EGHHJDHHBKM(EGHHJDHHBKM other) : this() {
    kJHDCEDJACN_ = other.kJHDCEDJACN_;
    fCONOFEKJMH_ = other.fCONOFEKJMH_;
    aMKAMCCPGHH_ = other.aMKAMCCPGHH_;
    fGNMJDDGHNA_ = other.fGNMJDDGHNA_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EGHHJDHHBKM Clone() {
    return new EGHHJDHHBKM(this);
  }

  /// <summary>Field number for the "KJHDCEDJACN" field.</summary>
  public const int KJHDCEDJACNFieldNumber = 1;
  private long kJHDCEDJACN_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long KJHDCEDJACN {
    get { return kJHDCEDJACN_; }
    set {
      kJHDCEDJACN_ = value;
    }
  }

  /// <summary>Field number for the "FCONOFEKJMH" field.</summary>
  public const int FCONOFEKJMHFieldNumber = 2;
  private long fCONOFEKJMH_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long FCONOFEKJMH {
    get { return fCONOFEKJMH_; }
    set {
      fCONOFEKJMH_ = value;
    }
  }

  /// <summary>Field number for the "AMKAMCCPGHH" field.</summary>
  public const int AMKAMCCPGHHFieldNumber = 3;
  private uint aMKAMCCPGHH_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint AMKAMCCPGHH {
    get { return aMKAMCCPGHH_; }
    set {
      aMKAMCCPGHH_ = value;
    }
  }

  /// <summary>Field number for the "FGNMJDDGHNA" field.</summary>
  public const int FGNMJDDGHNAFieldNumber = 4;
  private uint fGNMJDDGHNA_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint FGNMJDDGHNA {
    get { return fGNMJDDGHNA_; }
    set {
      fGNMJDDGHNA_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EGHHJDHHBKM);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EGHHJDHHBKM other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (KJHDCEDJACN != other.KJHDCEDJACN) return false;
    if (FCONOFEKJMH != other.FCONOFEKJMH) return false;
    if (AMKAMCCPGHH != other.AMKAMCCPGHH) return false;
    if (FGNMJDDGHNA != other.FGNMJDDGHNA) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (KJHDCEDJACN != 0L) hash ^= KJHDCEDJACN.GetHashCode();
    if (FCONOFEKJMH != 0L) hash ^= FCONOFEKJMH.GetHashCode();
    if (AMKAMCCPGHH != 0) hash ^= AMKAMCCPGHH.GetHashCode();
    if (FGNMJDDGHNA != 0) hash ^= FGNMJDDGHNA.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (KJHDCEDJACN != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(KJHDCEDJACN);
    }
    if (FCONOFEKJMH != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(FCONOFEKJMH);
    }
    if (AMKAMCCPGHH != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(AMKAMCCPGHH);
    }
    if (FGNMJDDGHNA != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(FGNMJDDGHNA);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (KJHDCEDJACN != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(KJHDCEDJACN);
    }
    if (FCONOFEKJMH != 0L) {
      output.WriteRawTag(16);
      output.WriteInt64(FCONOFEKJMH);
    }
    if (AMKAMCCPGHH != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(AMKAMCCPGHH);
    }
    if (FGNMJDDGHNA != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(FGNMJDDGHNA);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (KJHDCEDJACN != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(KJHDCEDJACN);
    }
    if (FCONOFEKJMH != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(FCONOFEKJMH);
    }
    if (AMKAMCCPGHH != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AMKAMCCPGHH);
    }
    if (FGNMJDDGHNA != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FGNMJDDGHNA);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EGHHJDHHBKM other) {
    if (other == null) {
      return;
    }
    if (other.KJHDCEDJACN != 0L) {
      KJHDCEDJACN = other.KJHDCEDJACN;
    }
    if (other.FCONOFEKJMH != 0L) {
      FCONOFEKJMH = other.FCONOFEKJMH;
    }
    if (other.AMKAMCCPGHH != 0) {
      AMKAMCCPGHH = other.AMKAMCCPGHH;
    }
    if (other.FGNMJDDGHNA != 0) {
      FGNMJDDGHNA = other.FGNMJDDGHNA;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          KJHDCEDJACN = input.ReadInt64();
          break;
        }
        case 16: {
          FCONOFEKJMH = input.ReadInt64();
          break;
        }
        case 24: {
          AMKAMCCPGHH = input.ReadUInt32();
          break;
        }
        case 32: {
          FGNMJDDGHNA = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          KJHDCEDJACN = input.ReadInt64();
          break;
        }
        case 16: {
          FCONOFEKJMH = input.ReadInt64();
          break;
        }
        case 24: {
          AMKAMCCPGHH = input.ReadUInt32();
          break;
        }
        case 32: {
          FGNMJDDGHNA = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
