// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetMissionStatusScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetMissionStatusScRsp.proto</summary>
public static partial class GetMissionStatusScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetMissionStatusScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetMissionStatusScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChtHZXRNaXNzaW9uU3RhdHVzU2NSc3AucHJvdG8i0AEKFUdldE1pc3Npb25T",
          "dGF0dXNTY1JzcBInCh91bmZpbmlzaGVkX21haW5fbWlzc2lvbl9pZF9saXN0",
          "GAMgAygNEisKGW1pc3Npb25fZXZlbnRfc3RhdHVzX2xpc3QYBCADKAsyCC5N",
          "aXNzaW9uEiUKHWZpbmlzaGVkX21haW5fbWlzc2lvbl9pZF9saXN0GAEgAygN",
          "EikKF3N1Yl9taXNzaW9uX3N0YXR1c19saXN0GAggAygLMgguTWlzc2lvbhIP",
          "CgdyZXRjb2RlGA8gASgNIkcKB01pc3Npb24SHgoGc3RhdHVzGAwgASgOMg4u",
          "TWlzc2lvblN0YXR1cxIKCgJpZBgIIAEoDRIQCghwcm9ncmVzcxgEIAEoDSpe",
          "Cg1NaXNzaW9uU3RhdHVzEhAKDE1JU1NJT05fTk9ORRAAEhEKDU1JU1NJT05f",
          "RE9JTkcQARISCg5NSVNTSU9OX0ZJTklTSBACEhQKEE1JU1NJT05fUFJFUEFS",
          "RUQQA2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MissionStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetMissionStatusScRsp), global::GetMissionStatusScRsp.Parser, new[]{ "UnfinishedMainMissionIdList", "MissionEventStatusList", "FinishedMainMissionIdList", "SubMissionStatusList", "Retcode" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Mission), global::Mission.Parser, new[]{ "Status", "Id", "Progress" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Enums
public enum MissionStatus {
  [pbr::OriginalName("MISSION_NONE")] MissionNone = 0,
  [pbr::OriginalName("MISSION_DOING")] MissionDoing = 1,
  [pbr::OriginalName("MISSION_FINISH")] MissionFinish = 2,
  [pbr::OriginalName("MISSION_PREPARED")] MissionPrepared = 3,
}

#endregion

#region Messages
public sealed partial class GetMissionStatusScRsp : pb::IMessage<GetMissionStatusScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetMissionStatusScRsp> _parser = new pb::MessageParser<GetMissionStatusScRsp>(() => new GetMissionStatusScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetMissionStatusScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetMissionStatusScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionStatusScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionStatusScRsp(GetMissionStatusScRsp other) : this() {
    unfinishedMainMissionIdList_ = other.unfinishedMainMissionIdList_.Clone();
    missionEventStatusList_ = other.missionEventStatusList_.Clone();
    finishedMainMissionIdList_ = other.finishedMainMissionIdList_.Clone();
    subMissionStatusList_ = other.subMissionStatusList_.Clone();
    retcode_ = other.retcode_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionStatusScRsp Clone() {
    return new GetMissionStatusScRsp(this);
  }

  /// <summary>Field number for the "unfinished_main_mission_id_list" field.</summary>
  public const int UnfinishedMainMissionIdListFieldNumber = 3;
  private static readonly pb::FieldCodec<uint> _repeated_unfinishedMainMissionIdList_codec
      = pb::FieldCodec.ForUInt32(26);
  private readonly pbc::RepeatedField<uint> unfinishedMainMissionIdList_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> UnfinishedMainMissionIdList {
    get { return unfinishedMainMissionIdList_; }
  }

  /// <summary>Field number for the "mission_event_status_list" field.</summary>
  public const int MissionEventStatusListFieldNumber = 4;
  private static readonly pb::FieldCodec<global::Mission> _repeated_missionEventStatusList_codec
      = pb::FieldCodec.ForMessage(34, global::Mission.Parser);
  private readonly pbc::RepeatedField<global::Mission> missionEventStatusList_ = new pbc::RepeatedField<global::Mission>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Mission> MissionEventStatusList {
    get { return missionEventStatusList_; }
  }

  /// <summary>Field number for the "finished_main_mission_id_list" field.</summary>
  public const int FinishedMainMissionIdListFieldNumber = 1;
  private static readonly pb::FieldCodec<uint> _repeated_finishedMainMissionIdList_codec
      = pb::FieldCodec.ForUInt32(10);
  private readonly pbc::RepeatedField<uint> finishedMainMissionIdList_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> FinishedMainMissionIdList {
    get { return finishedMainMissionIdList_; }
  }

  /// <summary>Field number for the "sub_mission_status_list" field.</summary>
  public const int SubMissionStatusListFieldNumber = 8;
  private static readonly pb::FieldCodec<global::Mission> _repeated_subMissionStatusList_codec
      = pb::FieldCodec.ForMessage(66, global::Mission.Parser);
  private readonly pbc::RepeatedField<global::Mission> subMissionStatusList_ = new pbc::RepeatedField<global::Mission>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Mission> SubMissionStatusList {
    get { return subMissionStatusList_; }
  }

  /// <summary>Field number for the "retcode" field.</summary>
  public const int RetcodeFieldNumber = 15;
  private uint retcode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Retcode {
    get { return retcode_; }
    set {
      retcode_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetMissionStatusScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetMissionStatusScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!unfinishedMainMissionIdList_.Equals(other.unfinishedMainMissionIdList_)) return false;
    if(!missionEventStatusList_.Equals(other.missionEventStatusList_)) return false;
    if(!finishedMainMissionIdList_.Equals(other.finishedMainMissionIdList_)) return false;
    if(!subMissionStatusList_.Equals(other.subMissionStatusList_)) return false;
    if (Retcode != other.Retcode) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= unfinishedMainMissionIdList_.GetHashCode();
    hash ^= missionEventStatusList_.GetHashCode();
    hash ^= finishedMainMissionIdList_.GetHashCode();
    hash ^= subMissionStatusList_.GetHashCode();
    if (Retcode != 0) hash ^= Retcode.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    finishedMainMissionIdList_.WriteTo(output, _repeated_finishedMainMissionIdList_codec);
    unfinishedMainMissionIdList_.WriteTo(output, _repeated_unfinishedMainMissionIdList_codec);
    missionEventStatusList_.WriteTo(output, _repeated_missionEventStatusList_codec);
    subMissionStatusList_.WriteTo(output, _repeated_subMissionStatusList_codec);
    if (Retcode != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(Retcode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    finishedMainMissionIdList_.WriteTo(ref output, _repeated_finishedMainMissionIdList_codec);
    unfinishedMainMissionIdList_.WriteTo(ref output, _repeated_unfinishedMainMissionIdList_codec);
    missionEventStatusList_.WriteTo(ref output, _repeated_missionEventStatusList_codec);
    subMissionStatusList_.WriteTo(ref output, _repeated_subMissionStatusList_codec);
    if (Retcode != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(Retcode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += unfinishedMainMissionIdList_.CalculateSize(_repeated_unfinishedMainMissionIdList_codec);
    size += missionEventStatusList_.CalculateSize(_repeated_missionEventStatusList_codec);
    size += finishedMainMissionIdList_.CalculateSize(_repeated_finishedMainMissionIdList_codec);
    size += subMissionStatusList_.CalculateSize(_repeated_subMissionStatusList_codec);
    if (Retcode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Retcode);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetMissionStatusScRsp other) {
    if (other == null) {
      return;
    }
    unfinishedMainMissionIdList_.Add(other.unfinishedMainMissionIdList_);
    missionEventStatusList_.Add(other.missionEventStatusList_);
    finishedMainMissionIdList_.Add(other.finishedMainMissionIdList_);
    subMissionStatusList_.Add(other.subMissionStatusList_);
    if (other.Retcode != 0) {
      Retcode = other.Retcode;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10:
        case 8: {
          finishedMainMissionIdList_.AddEntriesFrom(input, _repeated_finishedMainMissionIdList_codec);
          break;
        }
        case 26:
        case 24: {
          unfinishedMainMissionIdList_.AddEntriesFrom(input, _repeated_unfinishedMainMissionIdList_codec);
          break;
        }
        case 34: {
          missionEventStatusList_.AddEntriesFrom(input, _repeated_missionEventStatusList_codec);
          break;
        }
        case 66: {
          subMissionStatusList_.AddEntriesFrom(input, _repeated_subMissionStatusList_codec);
          break;
        }
        case 120: {
          Retcode = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10:
        case 8: {
          finishedMainMissionIdList_.AddEntriesFrom(ref input, _repeated_finishedMainMissionIdList_codec);
          break;
        }
        case 26:
        case 24: {
          unfinishedMainMissionIdList_.AddEntriesFrom(ref input, _repeated_unfinishedMainMissionIdList_codec);
          break;
        }
        case 34: {
          missionEventStatusList_.AddEntriesFrom(ref input, _repeated_missionEventStatusList_codec);
          break;
        }
        case 66: {
          subMissionStatusList_.AddEntriesFrom(ref input, _repeated_subMissionStatusList_codec);
          break;
        }
        case 120: {
          Retcode = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Mission : pb::IMessage<Mission>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Mission> _parser = new pb::MessageParser<Mission>(() => new Mission());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Mission> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetMissionStatusScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Mission() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Mission(Mission other) : this() {
    status_ = other.status_;
    id_ = other.id_;
    progress_ = other.progress_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Mission Clone() {
    return new Mission(this);
  }

  /// <summary>Field number for the "status" field.</summary>
  public const int StatusFieldNumber = 12;
  private global::MissionStatus status_ = global::MissionStatus.MissionNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::MissionStatus Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 8;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "progress" field.</summary>
  public const int ProgressFieldNumber = 4;
  private uint progress_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Progress {
    get { return progress_; }
    set {
      progress_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Mission);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Mission other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Status != other.Status) return false;
    if (Id != other.Id) return false;
    if (Progress != other.Progress) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Status != global::MissionStatus.MissionNone) hash ^= Status.GetHashCode();
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Progress != 0) hash ^= Progress.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Progress != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Progress);
    }
    if (Id != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(Id);
    }
    if (Status != global::MissionStatus.MissionNone) {
      output.WriteRawTag(96);
      output.WriteEnum((int) Status);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Progress != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(Progress);
    }
    if (Id != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(Id);
    }
    if (Status != global::MissionStatus.MissionNone) {
      output.WriteRawTag(96);
      output.WriteEnum((int) Status);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Status != global::MissionStatus.MissionNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
    }
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (Progress != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Progress);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Mission other) {
    if (other == null) {
      return;
    }
    if (other.Status != global::MissionStatus.MissionNone) {
      Status = other.Status;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Progress != 0) {
      Progress = other.Progress;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 32: {
          Progress = input.ReadUInt32();
          break;
        }
        case 64: {
          Id = input.ReadUInt32();
          break;
        }
        case 96: {
          Status = (global::MissionStatus) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 32: {
          Progress = input.ReadUInt32();
          break;
        }
        case 64: {
          Id = input.ReadUInt32();
          break;
        }
        case 96: {
          Status = (global::MissionStatus) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
