// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetMissionStatusReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetMissionStatusReq.proto</summary>
public static partial class GetMissionStatusReqReflection {

  #region Descriptor
  /// <summary>File descriptor for GetMissionStatusReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetMissionStatusReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlHZXRNaXNzaW9uU3RhdHVzUmVxLnByb3RvIl8KFUdldE1pc3Npb25TdGF0",
          "dXNDc1JlcRITCgtTdWJNaXNzaW9ucxgNIAMoDRIaChJVbmZpbmlzaGVkTWlz",
          "c2lvbnMYCCADKA0SFQoNRXZlbnRNaXNzaW9ucxgDIAMoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetMissionStatusCsReq), global::GetMissionStatusCsReq.Parser, new[]{ "SubMissions", "UnfinishedMissions", "EventMissions" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetMissionStatusCsReq : pb::IMessage<GetMissionStatusCsReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetMissionStatusCsReq> _parser = new pb::MessageParser<GetMissionStatusCsReq>(() => new GetMissionStatusCsReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetMissionStatusCsReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetMissionStatusReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionStatusCsReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionStatusCsReq(GetMissionStatusCsReq other) : this() {
    subMissions_ = other.subMissions_.Clone();
    unfinishedMissions_ = other.unfinishedMissions_.Clone();
    eventMissions_ = other.eventMissions_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetMissionStatusCsReq Clone() {
    return new GetMissionStatusCsReq(this);
  }

  /// <summary>Field number for the "SubMissions" field.</summary>
  public const int SubMissionsFieldNumber = 13;
  private static readonly pb::FieldCodec<uint> _repeated_subMissions_codec
      = pb::FieldCodec.ForUInt32(106);
  private readonly pbc::RepeatedField<uint> subMissions_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> SubMissions {
    get { return subMissions_; }
  }

  /// <summary>Field number for the "UnfinishedMissions" field.</summary>
  public const int UnfinishedMissionsFieldNumber = 8;
  private static readonly pb::FieldCodec<uint> _repeated_unfinishedMissions_codec
      = pb::FieldCodec.ForUInt32(66);
  private readonly pbc::RepeatedField<uint> unfinishedMissions_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> UnfinishedMissions {
    get { return unfinishedMissions_; }
  }

  /// <summary>Field number for the "EventMissions" field.</summary>
  public const int EventMissionsFieldNumber = 3;
  private static readonly pb::FieldCodec<uint> _repeated_eventMissions_codec
      = pb::FieldCodec.ForUInt32(26);
  private readonly pbc::RepeatedField<uint> eventMissions_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> EventMissions {
    get { return eventMissions_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetMissionStatusCsReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetMissionStatusCsReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!subMissions_.Equals(other.subMissions_)) return false;
    if(!unfinishedMissions_.Equals(other.unfinishedMissions_)) return false;
    if(!eventMissions_.Equals(other.eventMissions_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= subMissions_.GetHashCode();
    hash ^= unfinishedMissions_.GetHashCode();
    hash ^= eventMissions_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    eventMissions_.WriteTo(output, _repeated_eventMissions_codec);
    unfinishedMissions_.WriteTo(output, _repeated_unfinishedMissions_codec);
    subMissions_.WriteTo(output, _repeated_subMissions_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    eventMissions_.WriteTo(ref output, _repeated_eventMissions_codec);
    unfinishedMissions_.WriteTo(ref output, _repeated_unfinishedMissions_codec);
    subMissions_.WriteTo(ref output, _repeated_subMissions_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += subMissions_.CalculateSize(_repeated_subMissions_codec);
    size += unfinishedMissions_.CalculateSize(_repeated_unfinishedMissions_codec);
    size += eventMissions_.CalculateSize(_repeated_eventMissions_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetMissionStatusCsReq other) {
    if (other == null) {
      return;
    }
    subMissions_.Add(other.subMissions_);
    unfinishedMissions_.Add(other.unfinishedMissions_);
    eventMissions_.Add(other.eventMissions_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 26:
        case 24: {
          eventMissions_.AddEntriesFrom(input, _repeated_eventMissions_codec);
          break;
        }
        case 66:
        case 64: {
          unfinishedMissions_.AddEntriesFrom(input, _repeated_unfinishedMissions_codec);
          break;
        }
        case 106:
        case 104: {
          subMissions_.AddEntriesFrom(input, _repeated_subMissions_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 26:
        case 24: {
          eventMissions_.AddEntriesFrom(ref input, _repeated_eventMissions_codec);
          break;
        }
        case 66:
        case 64: {
          unfinishedMissions_.AddEntriesFrom(ref input, _repeated_unfinishedMissions_codec);
          break;
        }
        case 106:
        case 104: {
          subMissions_.AddEntriesFrom(ref input, _repeated_subMissions_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
