// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DoGachaCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from DoGachaCsReq.proto</summary>
public static partial class DoGachaCsReqReflection {

  #region Descriptor
  /// <summary>File descriptor for DoGachaCsReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DoGachaCsReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChJEb0dhY2hhQ3NSZXEucHJvdG8iVAoMRG9HYWNoYUNzUmVxEhEKCXJhbmRv",
          "bU51bRgJIAEoDRIPCgdnYWNoYUlEGA8gASgNEgsKA251bRgCIAEoDRITCgtu",
          "RkhOS05KR0JPRBgBIAEoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DoGachaCsReq), global::DoGachaCsReq.Parser, new[]{ "RandomNum", "GachaID", "Num", "NFHNKNJGBOD" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class DoGachaCsReq : pb::IMessage<DoGachaCsReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DoGachaCsReq> _parser = new pb::MessageParser<DoGachaCsReq>(() => new DoGachaCsReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DoGachaCsReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DoGachaCsReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DoGachaCsReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DoGachaCsReq(DoGachaCsReq other) : this() {
    randomNum_ = other.randomNum_;
    gachaID_ = other.gachaID_;
    num_ = other.num_;
    nFHNKNJGBOD_ = other.nFHNKNJGBOD_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DoGachaCsReq Clone() {
    return new DoGachaCsReq(this);
  }

  /// <summary>Field number for the "randomNum" field.</summary>
  public const int RandomNumFieldNumber = 9;
  private uint randomNum_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RandomNum {
    get { return randomNum_; }
    set {
      randomNum_ = value;
    }
  }

  /// <summary>Field number for the "gachaID" field.</summary>
  public const int GachaIDFieldNumber = 15;
  private uint gachaID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GachaID {
    get { return gachaID_; }
    set {
      gachaID_ = value;
    }
  }

  /// <summary>Field number for the "num" field.</summary>
  public const int NumFieldNumber = 2;
  private uint num_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Num {
    get { return num_; }
    set {
      num_ = value;
    }
  }

  /// <summary>Field number for the "nFHNKNJGBOD" field.</summary>
  public const int NFHNKNJGBODFieldNumber = 1;
  private uint nFHNKNJGBOD_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint NFHNKNJGBOD {
    get { return nFHNKNJGBOD_; }
    set {
      nFHNKNJGBOD_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DoGachaCsReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DoGachaCsReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (RandomNum != other.RandomNum) return false;
    if (GachaID != other.GachaID) return false;
    if (Num != other.Num) return false;
    if (NFHNKNJGBOD != other.NFHNKNJGBOD) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (RandomNum != 0) hash ^= RandomNum.GetHashCode();
    if (GachaID != 0) hash ^= GachaID.GetHashCode();
    if (Num != 0) hash ^= Num.GetHashCode();
    if (NFHNKNJGBOD != 0) hash ^= NFHNKNJGBOD.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (NFHNKNJGBOD != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(NFHNKNJGBOD);
    }
    if (Num != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Num);
    }
    if (RandomNum != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(RandomNum);
    }
    if (GachaID != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(GachaID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (NFHNKNJGBOD != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(NFHNKNJGBOD);
    }
    if (Num != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(Num);
    }
    if (RandomNum != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(RandomNum);
    }
    if (GachaID != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(GachaID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (RandomNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RandomNum);
    }
    if (GachaID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaID);
    }
    if (Num != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Num);
    }
    if (NFHNKNJGBOD != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(NFHNKNJGBOD);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DoGachaCsReq other) {
    if (other == null) {
      return;
    }
    if (other.RandomNum != 0) {
      RandomNum = other.RandomNum;
    }
    if (other.GachaID != 0) {
      GachaID = other.GachaID;
    }
    if (other.Num != 0) {
      Num = other.Num;
    }
    if (other.NFHNKNJGBOD != 0) {
      NFHNKNJGBOD = other.NFHNKNJGBOD;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          NFHNKNJGBOD = input.ReadUInt32();
          break;
        }
        case 16: {
          Num = input.ReadUInt32();
          break;
        }
        case 72: {
          RandomNum = input.ReadUInt32();
          break;
        }
        case 120: {
          GachaID = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          NFHNKNJGBOD = input.ReadUInt32();
          break;
        }
        case 16: {
          Num = input.ReadUInt32();
          break;
        }
        case 72: {
          RandomNum = input.ReadUInt32();
          break;
        }
        case 120: {
          GachaID = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
