// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetArchiveDataScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetArchiveDataScRsp.proto</summary>
public static partial class GetArchiveDataScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetArchiveDataScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetArchiveDataScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlHZXRBcmNoaXZlRGF0YVNjUnNwLnByb3RvIkkKE0dldEFyY2hpdmVEYXRh",
          "U2NSc3ASDwoHbV92YWx1ZRgIIAEoDRIhCgtuTUtCQ0FOR0lJSRgMIAEoCzIM",
          "LkxHQ0lNSU9GQkNQImgKC0xHQ0lNSU9GQkNQEiEKC29PQU5BRUZBREhEGAwg",
          "AygLMgwuSUpJTEdGUE9PR08SIQoLY05OTlBOTUFKTEsYDiADKAsyDC5FSUZH",
          "TkZDTEVJThITCgtlQkNCTUtGQk9PTRgGIAMoDSIvCgtJSklMR0ZQT09HTxIR",
          "Cgltb25zdGVySUQYDiABKA0SDQoFY291bnQYByABKA0iKgoLRUlGR05GQ0xF",
          "SU4SDQoFc2V0SUQYCSABKA0SDAoEdHlwZRgOIAEoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetArchiveDataScRsp), global::GetArchiveDataScRsp.Parser, new[]{ "MValue", "NMKBCANGIII" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LGCIMIOFBCP), global::LGCIMIOFBCP.Parser, new[]{ "OOANAEFADHD", "CNNNPNMAJLK", "EBCBMKFBOOM" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IJILGFPOOGO), global::IJILGFPOOGO.Parser, new[]{ "MonsterID", "Count" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EIFGNFCLEIN), global::EIFGNFCLEIN.Parser, new[]{ "SetID", "Type" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetArchiveDataScRsp : pb::IMessage<GetArchiveDataScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetArchiveDataScRsp> _parser = new pb::MessageParser<GetArchiveDataScRsp>(() => new GetArchiveDataScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetArchiveDataScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetArchiveDataScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetArchiveDataScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetArchiveDataScRsp(GetArchiveDataScRsp other) : this() {
    mValue_ = other.mValue_;
    nMKBCANGIII_ = other.nMKBCANGIII_ != null ? other.nMKBCANGIII_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetArchiveDataScRsp Clone() {
    return new GetArchiveDataScRsp(this);
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 8;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  /// <summary>Field number for the "nMKBCANGIII" field.</summary>
  public const int NMKBCANGIIIFieldNumber = 12;
  private global::LGCIMIOFBCP nMKBCANGIII_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::LGCIMIOFBCP NMKBCANGIII {
    get { return nMKBCANGIII_; }
    set {
      nMKBCANGIII_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetArchiveDataScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetArchiveDataScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MValue != other.MValue) return false;
    if (!object.Equals(NMKBCANGIII, other.NMKBCANGIII)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (nMKBCANGIII_ != null) hash ^= NMKBCANGIII.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MValue != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(MValue);
    }
    if (nMKBCANGIII_ != null) {
      output.WriteRawTag(98);
      output.WriteMessage(NMKBCANGIII);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MValue != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(MValue);
    }
    if (nMKBCANGIII_ != null) {
      output.WriteRawTag(98);
      output.WriteMessage(NMKBCANGIII);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (nMKBCANGIII_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(NMKBCANGIII);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetArchiveDataScRsp other) {
    if (other == null) {
      return;
    }
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    if (other.nMKBCANGIII_ != null) {
      if (nMKBCANGIII_ == null) {
        NMKBCANGIII = new global::LGCIMIOFBCP();
      }
      NMKBCANGIII.MergeFrom(other.NMKBCANGIII);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 64: {
          MValue = input.ReadUInt32();
          break;
        }
        case 98: {
          if (nMKBCANGIII_ == null) {
            NMKBCANGIII = new global::LGCIMIOFBCP();
          }
          input.ReadMessage(NMKBCANGIII);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 64: {
          MValue = input.ReadUInt32();
          break;
        }
        case 98: {
          if (nMKBCANGIII_ == null) {
            NMKBCANGIII = new global::LGCIMIOFBCP();
          }
          input.ReadMessage(NMKBCANGIII);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class LGCIMIOFBCP : pb::IMessage<LGCIMIOFBCP>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LGCIMIOFBCP> _parser = new pb::MessageParser<LGCIMIOFBCP>(() => new LGCIMIOFBCP());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LGCIMIOFBCP> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetArchiveDataScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LGCIMIOFBCP() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LGCIMIOFBCP(LGCIMIOFBCP other) : this() {
    oOANAEFADHD_ = other.oOANAEFADHD_.Clone();
    cNNNPNMAJLK_ = other.cNNNPNMAJLK_.Clone();
    eBCBMKFBOOM_ = other.eBCBMKFBOOM_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LGCIMIOFBCP Clone() {
    return new LGCIMIOFBCP(this);
  }

  /// <summary>Field number for the "oOANAEFADHD" field.</summary>
  public const int OOANAEFADHDFieldNumber = 12;
  private static readonly pb::FieldCodec<global::IJILGFPOOGO> _repeated_oOANAEFADHD_codec
      = pb::FieldCodec.ForMessage(98, global::IJILGFPOOGO.Parser);
  private readonly pbc::RepeatedField<global::IJILGFPOOGO> oOANAEFADHD_ = new pbc::RepeatedField<global::IJILGFPOOGO>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::IJILGFPOOGO> OOANAEFADHD {
    get { return oOANAEFADHD_; }
  }

  /// <summary>Field number for the "cNNNPNMAJLK" field.</summary>
  public const int CNNNPNMAJLKFieldNumber = 14;
  private static readonly pb::FieldCodec<global::EIFGNFCLEIN> _repeated_cNNNPNMAJLK_codec
      = pb::FieldCodec.ForMessage(114, global::EIFGNFCLEIN.Parser);
  private readonly pbc::RepeatedField<global::EIFGNFCLEIN> cNNNPNMAJLK_ = new pbc::RepeatedField<global::EIFGNFCLEIN>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EIFGNFCLEIN> CNNNPNMAJLK {
    get { return cNNNPNMAJLK_; }
  }

  /// <summary>Field number for the "eBCBMKFBOOM" field.</summary>
  public const int EBCBMKFBOOMFieldNumber = 6;
  private static readonly pb::FieldCodec<uint> _repeated_eBCBMKFBOOM_codec
      = pb::FieldCodec.ForUInt32(50);
  private readonly pbc::RepeatedField<uint> eBCBMKFBOOM_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> EBCBMKFBOOM {
    get { return eBCBMKFBOOM_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LGCIMIOFBCP);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LGCIMIOFBCP other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!oOANAEFADHD_.Equals(other.oOANAEFADHD_)) return false;
    if(!cNNNPNMAJLK_.Equals(other.cNNNPNMAJLK_)) return false;
    if(!eBCBMKFBOOM_.Equals(other.eBCBMKFBOOM_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= oOANAEFADHD_.GetHashCode();
    hash ^= cNNNPNMAJLK_.GetHashCode();
    hash ^= eBCBMKFBOOM_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    eBCBMKFBOOM_.WriteTo(output, _repeated_eBCBMKFBOOM_codec);
    oOANAEFADHD_.WriteTo(output, _repeated_oOANAEFADHD_codec);
    cNNNPNMAJLK_.WriteTo(output, _repeated_cNNNPNMAJLK_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    eBCBMKFBOOM_.WriteTo(ref output, _repeated_eBCBMKFBOOM_codec);
    oOANAEFADHD_.WriteTo(ref output, _repeated_oOANAEFADHD_codec);
    cNNNPNMAJLK_.WriteTo(ref output, _repeated_cNNNPNMAJLK_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += oOANAEFADHD_.CalculateSize(_repeated_oOANAEFADHD_codec);
    size += cNNNPNMAJLK_.CalculateSize(_repeated_cNNNPNMAJLK_codec);
    size += eBCBMKFBOOM_.CalculateSize(_repeated_eBCBMKFBOOM_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LGCIMIOFBCP other) {
    if (other == null) {
      return;
    }
    oOANAEFADHD_.Add(other.oOANAEFADHD_);
    cNNNPNMAJLK_.Add(other.cNNNPNMAJLK_);
    eBCBMKFBOOM_.Add(other.eBCBMKFBOOM_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 50:
        case 48: {
          eBCBMKFBOOM_.AddEntriesFrom(input, _repeated_eBCBMKFBOOM_codec);
          break;
        }
        case 98: {
          oOANAEFADHD_.AddEntriesFrom(input, _repeated_oOANAEFADHD_codec);
          break;
        }
        case 114: {
          cNNNPNMAJLK_.AddEntriesFrom(input, _repeated_cNNNPNMAJLK_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 50:
        case 48: {
          eBCBMKFBOOM_.AddEntriesFrom(ref input, _repeated_eBCBMKFBOOM_codec);
          break;
        }
        case 98: {
          oOANAEFADHD_.AddEntriesFrom(ref input, _repeated_oOANAEFADHD_codec);
          break;
        }
        case 114: {
          cNNNPNMAJLK_.AddEntriesFrom(ref input, _repeated_cNNNPNMAJLK_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class IJILGFPOOGO : pb::IMessage<IJILGFPOOGO>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<IJILGFPOOGO> _parser = new pb::MessageParser<IJILGFPOOGO>(() => new IJILGFPOOGO());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<IJILGFPOOGO> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetArchiveDataScRspReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IJILGFPOOGO() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IJILGFPOOGO(IJILGFPOOGO other) : this() {
    monsterID_ = other.monsterID_;
    count_ = other.count_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public IJILGFPOOGO Clone() {
    return new IJILGFPOOGO(this);
  }

  /// <summary>Field number for the "monsterID" field.</summary>
  public const int MonsterIDFieldNumber = 14;
  private uint monsterID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MonsterID {
    get { return monsterID_; }
    set {
      monsterID_ = value;
    }
  }

  /// <summary>Field number for the "count" field.</summary>
  public const int CountFieldNumber = 7;
  private uint count_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Count {
    get { return count_; }
    set {
      count_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as IJILGFPOOGO);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(IJILGFPOOGO other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (MonsterID != other.MonsterID) return false;
    if (Count != other.Count) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MonsterID != 0) hash ^= MonsterID.GetHashCode();
    if (Count != 0) hash ^= Count.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Count != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(Count);
    }
    if (MonsterID != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(MonsterID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Count != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(Count);
    }
    if (MonsterID != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(MonsterID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MonsterID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MonsterID);
    }
    if (Count != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Count);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(IJILGFPOOGO other) {
    if (other == null) {
      return;
    }
    if (other.MonsterID != 0) {
      MonsterID = other.MonsterID;
    }
    if (other.Count != 0) {
      Count = other.Count;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 56: {
          Count = input.ReadUInt32();
          break;
        }
        case 112: {
          MonsterID = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 56: {
          Count = input.ReadUInt32();
          break;
        }
        case 112: {
          MonsterID = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class EIFGNFCLEIN : pb::IMessage<EIFGNFCLEIN>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EIFGNFCLEIN> _parser = new pb::MessageParser<EIFGNFCLEIN>(() => new EIFGNFCLEIN());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EIFGNFCLEIN> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetArchiveDataScRspReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EIFGNFCLEIN() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EIFGNFCLEIN(EIFGNFCLEIN other) : this() {
    setID_ = other.setID_;
    type_ = other.type_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EIFGNFCLEIN Clone() {
    return new EIFGNFCLEIN(this);
  }

  /// <summary>Field number for the "setID" field.</summary>
  public const int SetIDFieldNumber = 9;
  private uint setID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SetID {
    get { return setID_; }
    set {
      setID_ = value;
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 14;
  private uint type_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EIFGNFCLEIN);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EIFGNFCLEIN other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (SetID != other.SetID) return false;
    if (Type != other.Type) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (SetID != 0) hash ^= SetID.GetHashCode();
    if (Type != 0) hash ^= Type.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (SetID != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(SetID);
    }
    if (Type != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (SetID != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(SetID);
    }
    if (Type != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(Type);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (SetID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SetID);
    }
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Type);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EIFGNFCLEIN other) {
    if (other == null) {
      return;
    }
    if (other.SetID != 0) {
      SetID = other.SetID;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 72: {
          SetID = input.ReadUInt32();
          break;
        }
        case 112: {
          Type = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 72: {
          SetID = input.ReadUInt32();
          break;
        }
        case 112: {
          Type = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
