// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetExpeditionDataScRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetExpeditionDataScRsp.proto</summary>
public static partial class GetExpeditionDataScRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetExpeditionDataScRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetExpeditionDataScRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChxHZXRFeHBlZGl0aW9uRGF0YVNjUnNwLnByb3RvInYKFkdldEV4cGVkaXRp",
          "b25EYXRhU2NSc3ASEwoLYkhMSURBSktJRUcYCCADKA0SIQoLbUdHQ0pBRkhD",
          "SkcYDyADKAsyDC5FSkJITU5QRkZDRBITCgtpSkpMSUdFSkxLUBgEIAEoDRIP",
          "CgdtX3ZhbHVlGAkgASgNIlYKC0VKQkhNTlBGRkNEEgoKAmlkGAcgASgNEhEK",
          "CV9EdXJhdGlvbhgBIAEoDRITCgtfQWNjZXB0VGltZRgJIAEoAxITCgtmTEdB",
          "QkZKTkRLSBgCIAMoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetExpeditionDataScRsp), global::GetExpeditionDataScRsp.Parser, new[]{ "BHLIDAJKIEG", "MGGCJAFHCJG", "IJJLIGEJLKP", "MValue" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EJBHMNPFFCD), global::EJBHMNPFFCD.Parser, new[]{ "Id", "Duration", "AcceptTime", "FLGABFJNDKH" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class GetExpeditionDataScRsp : pb::IMessage<GetExpeditionDataScRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetExpeditionDataScRsp> _parser = new pb::MessageParser<GetExpeditionDataScRsp>(() => new GetExpeditionDataScRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetExpeditionDataScRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetExpeditionDataScRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetExpeditionDataScRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetExpeditionDataScRsp(GetExpeditionDataScRsp other) : this() {
    bHLIDAJKIEG_ = other.bHLIDAJKIEG_.Clone();
    mGGCJAFHCJG_ = other.mGGCJAFHCJG_.Clone();
    iJJLIGEJLKP_ = other.iJJLIGEJLKP_;
    mValue_ = other.mValue_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetExpeditionDataScRsp Clone() {
    return new GetExpeditionDataScRsp(this);
  }

  /// <summary>Field number for the "bHLIDAJKIEG" field.</summary>
  public const int BHLIDAJKIEGFieldNumber = 8;
  private static readonly pb::FieldCodec<uint> _repeated_bHLIDAJKIEG_codec
      = pb::FieldCodec.ForUInt32(66);
  private readonly pbc::RepeatedField<uint> bHLIDAJKIEG_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> BHLIDAJKIEG {
    get { return bHLIDAJKIEG_; }
  }

  /// <summary>Field number for the "mGGCJAFHCJG" field.</summary>
  public const int MGGCJAFHCJGFieldNumber = 15;
  private static readonly pb::FieldCodec<global::EJBHMNPFFCD> _repeated_mGGCJAFHCJG_codec
      = pb::FieldCodec.ForMessage(122, global::EJBHMNPFFCD.Parser);
  private readonly pbc::RepeatedField<global::EJBHMNPFFCD> mGGCJAFHCJG_ = new pbc::RepeatedField<global::EJBHMNPFFCD>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::EJBHMNPFFCD> MGGCJAFHCJG {
    get { return mGGCJAFHCJG_; }
  }

  /// <summary>Field number for the "iJJLIGEJLKP" field.</summary>
  public const int IJJLIGEJLKPFieldNumber = 4;
  private uint iJJLIGEJLKP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint IJJLIGEJLKP {
    get { return iJJLIGEJLKP_; }
    set {
      iJJLIGEJLKP_ = value;
    }
  }

  /// <summary>Field number for the "m_value" field.</summary>
  public const int MValueFieldNumber = 9;
  private uint mValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MValue {
    get { return mValue_; }
    set {
      mValue_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetExpeditionDataScRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetExpeditionDataScRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!bHLIDAJKIEG_.Equals(other.bHLIDAJKIEG_)) return false;
    if(!mGGCJAFHCJG_.Equals(other.mGGCJAFHCJG_)) return false;
    if (IJJLIGEJLKP != other.IJJLIGEJLKP) return false;
    if (MValue != other.MValue) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= bHLIDAJKIEG_.GetHashCode();
    hash ^= mGGCJAFHCJG_.GetHashCode();
    if (IJJLIGEJLKP != 0) hash ^= IJJLIGEJLKP.GetHashCode();
    if (MValue != 0) hash ^= MValue.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (IJJLIGEJLKP != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(IJJLIGEJLKP);
    }
    bHLIDAJKIEG_.WriteTo(output, _repeated_bHLIDAJKIEG_codec);
    if (MValue != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(MValue);
    }
    mGGCJAFHCJG_.WriteTo(output, _repeated_mGGCJAFHCJG_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (IJJLIGEJLKP != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(IJJLIGEJLKP);
    }
    bHLIDAJKIEG_.WriteTo(ref output, _repeated_bHLIDAJKIEG_codec);
    if (MValue != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(MValue);
    }
    mGGCJAFHCJG_.WriteTo(ref output, _repeated_mGGCJAFHCJG_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += bHLIDAJKIEG_.CalculateSize(_repeated_bHLIDAJKIEG_codec);
    size += mGGCJAFHCJG_.CalculateSize(_repeated_mGGCJAFHCJG_codec);
    if (IJJLIGEJLKP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IJJLIGEJLKP);
    }
    if (MValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MValue);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetExpeditionDataScRsp other) {
    if (other == null) {
      return;
    }
    bHLIDAJKIEG_.Add(other.bHLIDAJKIEG_);
    mGGCJAFHCJG_.Add(other.mGGCJAFHCJG_);
    if (other.IJJLIGEJLKP != 0) {
      IJJLIGEJLKP = other.IJJLIGEJLKP;
    }
    if (other.MValue != 0) {
      MValue = other.MValue;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 32: {
          IJJLIGEJLKP = input.ReadUInt32();
          break;
        }
        case 66:
        case 64: {
          bHLIDAJKIEG_.AddEntriesFrom(input, _repeated_bHLIDAJKIEG_codec);
          break;
        }
        case 72: {
          MValue = input.ReadUInt32();
          break;
        }
        case 122: {
          mGGCJAFHCJG_.AddEntriesFrom(input, _repeated_mGGCJAFHCJG_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 32: {
          IJJLIGEJLKP = input.ReadUInt32();
          break;
        }
        case 66:
        case 64: {
          bHLIDAJKIEG_.AddEntriesFrom(ref input, _repeated_bHLIDAJKIEG_codec);
          break;
        }
        case 72: {
          MValue = input.ReadUInt32();
          break;
        }
        case 122: {
          mGGCJAFHCJG_.AddEntriesFrom(ref input, _repeated_mGGCJAFHCJG_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class EJBHMNPFFCD : pb::IMessage<EJBHMNPFFCD>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EJBHMNPFFCD> _parser = new pb::MessageParser<EJBHMNPFFCD>(() => new EJBHMNPFFCD());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EJBHMNPFFCD> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetExpeditionDataScRspReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EJBHMNPFFCD() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EJBHMNPFFCD(EJBHMNPFFCD other) : this() {
    id_ = other.id_;
    Duration_ = other.Duration_;
    AcceptTime_ = other.AcceptTime_;
    fLGABFJNDKH_ = other.fLGABFJNDKH_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EJBHMNPFFCD Clone() {
    return new EJBHMNPFFCD(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 7;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "_Duration" field.</summary>
  public const int DurationFieldNumber = 1;
  private uint Duration_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Duration {
    get { return Duration_; }
    set {
      Duration_ = value;
    }
  }

  /// <summary>Field number for the "_AcceptTime" field.</summary>
  public const int AcceptTimeFieldNumber = 9;
  private long AcceptTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long AcceptTime {
    get { return AcceptTime_; }
    set {
      AcceptTime_ = value;
    }
  }

  /// <summary>Field number for the "fLGABFJNDKH" field.</summary>
  public const int FLGABFJNDKHFieldNumber = 2;
  private static readonly pb::FieldCodec<uint> _repeated_fLGABFJNDKH_codec
      = pb::FieldCodec.ForUInt32(18);
  private readonly pbc::RepeatedField<uint> fLGABFJNDKH_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> FLGABFJNDKH {
    get { return fLGABFJNDKH_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EJBHMNPFFCD);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EJBHMNPFFCD other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Duration != other.Duration) return false;
    if (AcceptTime != other.AcceptTime) return false;
    if(!fLGABFJNDKH_.Equals(other.fLGABFJNDKH_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Duration != 0) hash ^= Duration.GetHashCode();
    if (AcceptTime != 0L) hash ^= AcceptTime.GetHashCode();
    hash ^= fLGABFJNDKH_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Duration != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Duration);
    }
    fLGABFJNDKH_.WriteTo(output, _repeated_fLGABFJNDKH_codec);
    if (Id != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(Id);
    }
    if (AcceptTime != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(AcceptTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Duration != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Duration);
    }
    fLGABFJNDKH_.WriteTo(ref output, _repeated_fLGABFJNDKH_codec);
    if (Id != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(Id);
    }
    if (AcceptTime != 0L) {
      output.WriteRawTag(72);
      output.WriteInt64(AcceptTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (Duration != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Duration);
    }
    if (AcceptTime != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(AcceptTime);
    }
    size += fLGABFJNDKH_.CalculateSize(_repeated_fLGABFJNDKH_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EJBHMNPFFCD other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Duration != 0) {
      Duration = other.Duration;
    }
    if (other.AcceptTime != 0L) {
      AcceptTime = other.AcceptTime;
    }
    fLGABFJNDKH_.Add(other.fLGABFJNDKH_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Duration = input.ReadUInt32();
          break;
        }
        case 18:
        case 16: {
          fLGABFJNDKH_.AddEntriesFrom(input, _repeated_fLGABFJNDKH_codec);
          break;
        }
        case 56: {
          Id = input.ReadUInt32();
          break;
        }
        case 72: {
          AcceptTime = input.ReadInt64();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Duration = input.ReadUInt32();
          break;
        }
        case 18:
        case 16: {
          fLGABFJNDKH_.AddEntriesFrom(ref input, _repeated_fLGABFJNDKH_codec);
          break;
        }
        case 56: {
          Id = input.ReadUInt32();
          break;
        }
        case 72: {
          AcceptTime = input.ReadInt64();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
