// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerHeartBeatReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PlayerHeartBeatReq.proto</summary>
public static partial class PlayerHeartBeatReqReflection {

  #region Descriptor
  /// <summary>File descriptor for PlayerHeartBeatReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerHeartBeatReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhQbGF5ZXJIZWFydEJlYXRSZXEucHJvdG8iWgoLQUtGRUFBRE5EQk0SEwoL",
          "TEJQRk5FQkVBQ0sYDCABKA0SIQoLR0FQRERBRUNIQVAYBiABKAsyDC5EUEtP",
          "SUhIRkdQRxITCgtGR05JSUFITkNDTRgDIAEoBCI3CgtEUEtPSUhIRkdQRxIT",
          "CgtiQ0NFRUZDSU5NUBgBIAEoCRITCgtjSU9LR09LTEZQRxgCIAEoCWIGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AKFEAADNDBM), global::AKFEAADNDBM.Parser, new[]{ "LBPFNEBEACK", "GAPDDAECHAP", "FGNIIAHNCCM" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DPKOIHHFGPG), global::DPKOIHHFGPG.Parser, new[]{ "BCCEEFCINMP", "CIOKGOKLFPG" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class AKFEAADNDBM : pb::IMessage<AKFEAADNDBM>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AKFEAADNDBM> _parser = new pb::MessageParser<AKFEAADNDBM>(() => new AKFEAADNDBM());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AKFEAADNDBM> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerHeartBeatReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AKFEAADNDBM() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AKFEAADNDBM(AKFEAADNDBM other) : this() {
    lBPFNEBEACK_ = other.lBPFNEBEACK_;
    gAPDDAECHAP_ = other.gAPDDAECHAP_ != null ? other.gAPDDAECHAP_.Clone() : null;
    fGNIIAHNCCM_ = other.fGNIIAHNCCM_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AKFEAADNDBM Clone() {
    return new AKFEAADNDBM(this);
  }

  /// <summary>Field number for the "LBPFNEBEACK" field.</summary>
  public const int LBPFNEBEACKFieldNumber = 12;
  private uint lBPFNEBEACK_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint LBPFNEBEACK {
    get { return lBPFNEBEACK_; }
    set {
      lBPFNEBEACK_ = value;
    }
  }

  /// <summary>Field number for the "GAPDDAECHAP" field.</summary>
  public const int GAPDDAECHAPFieldNumber = 6;
  private global::DPKOIHHFGPG gAPDDAECHAP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::DPKOIHHFGPG GAPDDAECHAP {
    get { return gAPDDAECHAP_; }
    set {
      gAPDDAECHAP_ = value;
    }
  }

  /// <summary>Field number for the "FGNIIAHNCCM" field.</summary>
  public const int FGNIIAHNCCMFieldNumber = 3;
  private ulong fGNIIAHNCCM_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong FGNIIAHNCCM {
    get { return fGNIIAHNCCM_; }
    set {
      fGNIIAHNCCM_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AKFEAADNDBM);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AKFEAADNDBM other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LBPFNEBEACK != other.LBPFNEBEACK) return false;
    if (!object.Equals(GAPDDAECHAP, other.GAPDDAECHAP)) return false;
    if (FGNIIAHNCCM != other.FGNIIAHNCCM) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (LBPFNEBEACK != 0) hash ^= LBPFNEBEACK.GetHashCode();
    if (gAPDDAECHAP_ != null) hash ^= GAPDDAECHAP.GetHashCode();
    if (FGNIIAHNCCM != 0UL) hash ^= FGNIIAHNCCM.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (FGNIIAHNCCM != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(FGNIIAHNCCM);
    }
    if (gAPDDAECHAP_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(GAPDDAECHAP);
    }
    if (LBPFNEBEACK != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(LBPFNEBEACK);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (FGNIIAHNCCM != 0UL) {
      output.WriteRawTag(24);
      output.WriteUInt64(FGNIIAHNCCM);
    }
    if (gAPDDAECHAP_ != null) {
      output.WriteRawTag(50);
      output.WriteMessage(GAPDDAECHAP);
    }
    if (LBPFNEBEACK != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(LBPFNEBEACK);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (LBPFNEBEACK != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LBPFNEBEACK);
    }
    if (gAPDDAECHAP_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(GAPDDAECHAP);
    }
    if (FGNIIAHNCCM != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(FGNIIAHNCCM);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AKFEAADNDBM other) {
    if (other == null) {
      return;
    }
    if (other.LBPFNEBEACK != 0) {
      LBPFNEBEACK = other.LBPFNEBEACK;
    }
    if (other.gAPDDAECHAP_ != null) {
      if (gAPDDAECHAP_ == null) {
        GAPDDAECHAP = new global::DPKOIHHFGPG();
      }
      GAPDDAECHAP.MergeFrom(other.GAPDDAECHAP);
    }
    if (other.FGNIIAHNCCM != 0UL) {
      FGNIIAHNCCM = other.FGNIIAHNCCM;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 24: {
          FGNIIAHNCCM = input.ReadUInt64();
          break;
        }
        case 50: {
          if (gAPDDAECHAP_ == null) {
            GAPDDAECHAP = new global::DPKOIHHFGPG();
          }
          input.ReadMessage(GAPDDAECHAP);
          break;
        }
        case 96: {
          LBPFNEBEACK = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 24: {
          FGNIIAHNCCM = input.ReadUInt64();
          break;
        }
        case 50: {
          if (gAPDDAECHAP_ == null) {
            GAPDDAECHAP = new global::DPKOIHHFGPG();
          }
          input.ReadMessage(GAPDDAECHAP);
          break;
        }
        case 96: {
          LBPFNEBEACK = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class DPKOIHHFGPG : pb::IMessage<DPKOIHHFGPG>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DPKOIHHFGPG> _parser = new pb::MessageParser<DPKOIHHFGPG>(() => new DPKOIHHFGPG());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DPKOIHHFGPG> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerHeartBeatReqReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DPKOIHHFGPG() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DPKOIHHFGPG(DPKOIHHFGPG other) : this() {
    bCCEEFCINMP_ = other.bCCEEFCINMP_;
    cIOKGOKLFPG_ = other.cIOKGOKLFPG_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DPKOIHHFGPG Clone() {
    return new DPKOIHHFGPG(this);
  }

  /// <summary>Field number for the "bCCEEFCINMP" field.</summary>
  public const int BCCEEFCINMPFieldNumber = 1;
  private string bCCEEFCINMP_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string BCCEEFCINMP {
    get { return bCCEEFCINMP_; }
    set {
      bCCEEFCINMP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "cIOKGOKLFPG" field.</summary>
  public const int CIOKGOKLFPGFieldNumber = 2;
  private string cIOKGOKLFPG_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string CIOKGOKLFPG {
    get { return cIOKGOKLFPG_; }
    set {
      cIOKGOKLFPG_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DPKOIHHFGPG);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DPKOIHHFGPG other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (BCCEEFCINMP != other.BCCEEFCINMP) return false;
    if (CIOKGOKLFPG != other.CIOKGOKLFPG) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (BCCEEFCINMP.Length != 0) hash ^= BCCEEFCINMP.GetHashCode();
    if (CIOKGOKLFPG.Length != 0) hash ^= CIOKGOKLFPG.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (BCCEEFCINMP.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(BCCEEFCINMP);
    }
    if (CIOKGOKLFPG.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CIOKGOKLFPG);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (BCCEEFCINMP.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(BCCEEFCINMP);
    }
    if (CIOKGOKLFPG.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(CIOKGOKLFPG);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (BCCEEFCINMP.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(BCCEEFCINMP);
    }
    if (CIOKGOKLFPG.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(CIOKGOKLFPG);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DPKOIHHFGPG other) {
    if (other == null) {
      return;
    }
    if (other.BCCEEFCINMP.Length != 0) {
      BCCEEFCINMP = other.BCCEEFCINMP;
    }
    if (other.CIOKGOKLFPG.Length != 0) {
      CIOKGOKLFPG = other.CIOKGOKLFPG;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          BCCEEFCINMP = input.ReadString();
          break;
        }
        case 18: {
          CIOKGOKLFPG = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          BCCEEFCINMP = input.ReadString();
          break;
        }
        case 18: {
          CIOKGOKLFPG = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
