// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerGetTokenCsReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PlayerGetTokenCsReq.proto</summary>
public static partial class PlayerGetTokenCsReqReflection {

  #region Descriptor
  /// <summary>File descriptor for PlayerGetTokenCsReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerGetTokenCsReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlQbGF5ZXJHZXRUb2tlbkNzUmVxLnByb3RvIrUBChNQbGF5ZXJHZXRUb2tl",
          "bkNzUmVxEhMKC2hPTUxPTUlCTUtIGA8gASgJEhIKCmdsb2JhbFZhcnMYBiAB",
          "KA0SEwoLYUFCTEdORUZQTUkYAyABKAkSEwoLcFBJRUFLT01BS0QYDSABKAkS",
          "CwoDdUlEGAUgASgNEhQKDHBsYXRmb3JtVHlwZRgEIAEoDRITCgtmQUNMQk1H",
          "Sk1HSxgIIAEoDRITCgtlQUhIQ0tCT0dGQRgOIAEoDWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PlayerGetTokenCsReq), global::PlayerGetTokenCsReq.Parser, new[]{ "HOMLOMIBMKH", "GlobalVars", "AABLGNEFPMI", "PPIEAKOMAKD", "UID", "PlatformType", "FACLBMGJMGK", "EAHHCKBOGFA" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PlayerGetTokenCsReq : pb::IMessage<PlayerGetTokenCsReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PlayerGetTokenCsReq> _parser = new pb::MessageParser<PlayerGetTokenCsReq>(() => new PlayerGetTokenCsReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PlayerGetTokenCsReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PlayerGetTokenCsReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerGetTokenCsReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerGetTokenCsReq(PlayerGetTokenCsReq other) : this() {
    hOMLOMIBMKH_ = other.hOMLOMIBMKH_;
    globalVars_ = other.globalVars_;
    aABLGNEFPMI_ = other.aABLGNEFPMI_;
    pPIEAKOMAKD_ = other.pPIEAKOMAKD_;
    uID_ = other.uID_;
    platformType_ = other.platformType_;
    fACLBMGJMGK_ = other.fACLBMGJMGK_;
    eAHHCKBOGFA_ = other.eAHHCKBOGFA_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PlayerGetTokenCsReq Clone() {
    return new PlayerGetTokenCsReq(this);
  }

  /// <summary>Field number for the "hOMLOMIBMKH" field.</summary>
  public const int HOMLOMIBMKHFieldNumber = 15;
  private string hOMLOMIBMKH_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string HOMLOMIBMKH {
    get { return hOMLOMIBMKH_; }
    set {
      hOMLOMIBMKH_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "globalVars" field.</summary>
  public const int GlobalVarsFieldNumber = 6;
  private uint globalVars_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GlobalVars {
    get { return globalVars_; }
    set {
      globalVars_ = value;
    }
  }

  /// <summary>Field number for the "aABLGNEFPMI" field.</summary>
  public const int AABLGNEFPMIFieldNumber = 3;
  private string aABLGNEFPMI_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AABLGNEFPMI {
    get { return aABLGNEFPMI_; }
    set {
      aABLGNEFPMI_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "pPIEAKOMAKD" field.</summary>
  public const int PPIEAKOMAKDFieldNumber = 13;
  private string pPIEAKOMAKD_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string PPIEAKOMAKD {
    get { return pPIEAKOMAKD_; }
    set {
      pPIEAKOMAKD_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "uID" field.</summary>
  public const int UIDFieldNumber = 5;
  private uint uID_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint UID {
    get { return uID_; }
    set {
      uID_ = value;
    }
  }

  /// <summary>Field number for the "platformType" field.</summary>
  public const int PlatformTypeFieldNumber = 4;
  private uint platformType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PlatformType {
    get { return platformType_; }
    set {
      platformType_ = value;
    }
  }

  /// <summary>Field number for the "fACLBMGJMGK" field.</summary>
  public const int FACLBMGJMGKFieldNumber = 8;
  private uint fACLBMGJMGK_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint FACLBMGJMGK {
    get { return fACLBMGJMGK_; }
    set {
      fACLBMGJMGK_ = value;
    }
  }

  /// <summary>Field number for the "eAHHCKBOGFA" field.</summary>
  public const int EAHHCKBOGFAFieldNumber = 14;
  private uint eAHHCKBOGFA_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EAHHCKBOGFA {
    get { return eAHHCKBOGFA_; }
    set {
      eAHHCKBOGFA_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PlayerGetTokenCsReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PlayerGetTokenCsReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HOMLOMIBMKH != other.HOMLOMIBMKH) return false;
    if (GlobalVars != other.GlobalVars) return false;
    if (AABLGNEFPMI != other.AABLGNEFPMI) return false;
    if (PPIEAKOMAKD != other.PPIEAKOMAKD) return false;
    if (UID != other.UID) return false;
    if (PlatformType != other.PlatformType) return false;
    if (FACLBMGJMGK != other.FACLBMGJMGK) return false;
    if (EAHHCKBOGFA != other.EAHHCKBOGFA) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HOMLOMIBMKH.Length != 0) hash ^= HOMLOMIBMKH.GetHashCode();
    if (GlobalVars != 0) hash ^= GlobalVars.GetHashCode();
    if (AABLGNEFPMI.Length != 0) hash ^= AABLGNEFPMI.GetHashCode();
    if (PPIEAKOMAKD.Length != 0) hash ^= PPIEAKOMAKD.GetHashCode();
    if (UID != 0) hash ^= UID.GetHashCode();
    if (PlatformType != 0) hash ^= PlatformType.GetHashCode();
    if (FACLBMGJMGK != 0) hash ^= FACLBMGJMGK.GetHashCode();
    if (EAHHCKBOGFA != 0) hash ^= EAHHCKBOGFA.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (AABLGNEFPMI.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AABLGNEFPMI);
    }
    if (PlatformType != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(PlatformType);
    }
    if (UID != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(UID);
    }
    if (GlobalVars != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(GlobalVars);
    }
    if (FACLBMGJMGK != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(FACLBMGJMGK);
    }
    if (PPIEAKOMAKD.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(PPIEAKOMAKD);
    }
    if (EAHHCKBOGFA != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(EAHHCKBOGFA);
    }
    if (HOMLOMIBMKH.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(HOMLOMIBMKH);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (AABLGNEFPMI.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(AABLGNEFPMI);
    }
    if (PlatformType != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(PlatformType);
    }
    if (UID != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(UID);
    }
    if (GlobalVars != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(GlobalVars);
    }
    if (FACLBMGJMGK != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(FACLBMGJMGK);
    }
    if (PPIEAKOMAKD.Length != 0) {
      output.WriteRawTag(106);
      output.WriteString(PPIEAKOMAKD);
    }
    if (EAHHCKBOGFA != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(EAHHCKBOGFA);
    }
    if (HOMLOMIBMKH.Length != 0) {
      output.WriteRawTag(122);
      output.WriteString(HOMLOMIBMKH);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HOMLOMIBMKH.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HOMLOMIBMKH);
    }
    if (GlobalVars != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GlobalVars);
    }
    if (AABLGNEFPMI.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AABLGNEFPMI);
    }
    if (PPIEAKOMAKD.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(PPIEAKOMAKD);
    }
    if (UID != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UID);
    }
    if (PlatformType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PlatformType);
    }
    if (FACLBMGJMGK != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FACLBMGJMGK);
    }
    if (EAHHCKBOGFA != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EAHHCKBOGFA);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PlayerGetTokenCsReq other) {
    if (other == null) {
      return;
    }
    if (other.HOMLOMIBMKH.Length != 0) {
      HOMLOMIBMKH = other.HOMLOMIBMKH;
    }
    if (other.GlobalVars != 0) {
      GlobalVars = other.GlobalVars;
    }
    if (other.AABLGNEFPMI.Length != 0) {
      AABLGNEFPMI = other.AABLGNEFPMI;
    }
    if (other.PPIEAKOMAKD.Length != 0) {
      PPIEAKOMAKD = other.PPIEAKOMAKD;
    }
    if (other.UID != 0) {
      UID = other.UID;
    }
    if (other.PlatformType != 0) {
      PlatformType = other.PlatformType;
    }
    if (other.FACLBMGJMGK != 0) {
      FACLBMGJMGK = other.FACLBMGJMGK;
    }
    if (other.EAHHCKBOGFA != 0) {
      EAHHCKBOGFA = other.EAHHCKBOGFA;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 26: {
          AABLGNEFPMI = input.ReadString();
          break;
        }
        case 32: {
          PlatformType = input.ReadUInt32();
          break;
        }
        case 40: {
          UID = input.ReadUInt32();
          break;
        }
        case 48: {
          GlobalVars = input.ReadUInt32();
          break;
        }
        case 64: {
          FACLBMGJMGK = input.ReadUInt32();
          break;
        }
        case 106: {
          PPIEAKOMAKD = input.ReadString();
          break;
        }
        case 112: {
          EAHHCKBOGFA = input.ReadUInt32();
          break;
        }
        case 122: {
          HOMLOMIBMKH = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 26: {
          AABLGNEFPMI = input.ReadString();
          break;
        }
        case 32: {
          PlatformType = input.ReadUInt32();
          break;
        }
        case 40: {
          UID = input.ReadUInt32();
          break;
        }
        case 48: {
          GlobalVars = input.ReadUInt32();
          break;
        }
        case 64: {
          FACLBMGJMGK = input.ReadUInt32();
          break;
        }
        case 106: {
          PPIEAKOMAKD = input.ReadString();
          break;
        }
        case 112: {
          EAHHCKBOGFA = input.ReadUInt32();
          break;
        }
        case 122: {
          HOMLOMIBMKH = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code